// Generated by Supabase from the live DB (project ref ohuhilcqluniqnkxiqhr).
// To refresh: regenerate types from Supabase (MCP `generate_typescript_types`
// or `supabase gen types typescript`) and replace this file.
// Do not edit by hand.
// Note: `profile.email` is present here (types reflect columns, not grants) but
// its SELECT is revoked from anon/authenticated — do not select it client-side.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.15"
  }
  public: {
    Tables: {
      instrument: {
        Row: {
          created_at: string
          id: number
          name: string | null
        }
        Insert: {
          created_at?: string
          id?: number
          name?: string | null
        }
        Update: {
          created_at?: string
          id?: number
          name?: string | null
        }
        Relationships: []
      }
      party: {
        Row: {
          approved_by_venue: boolean
          cancel_reason: string | null
          created_at: string
          created_by: string | null
          date: string | null
          description: string | null
          id: number
          status: Database["public"]["Enums"]["party_status"]
          status_changed_at: string
          title: string | null
          venue: number | null
        }
        Insert: {
          approved_by_venue?: boolean
          cancel_reason?: string | null
          created_at?: string
          created_by?: string | null
          date?: string | null
          description?: string | null
          id?: number
          status?: Database["public"]["Enums"]["party_status"]
          status_changed_at?: string
          title?: string | null
          venue?: number | null
        }
        Update: {
          approved_by_venue?: boolean
          cancel_reason?: string | null
          created_at?: string
          created_by?: string | null
          date?: string | null
          description?: string | null
          id?: number
          status?: Database["public"]["Enums"]["party_status"]
          status_changed_at?: string
          title?: string | null
          venue?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "party_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profile"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "party_venue_fkey"
            columns: ["venue"]
            isOneToOne: false
            referencedRelation: "venue"
            referencedColumns: ["id"]
          },
        ]
      }
      party_admin: {
        Row: {
          created_at: string
          party_id: number
          user_id: string
        }
        Insert: {
          created_at?: string
          party_id: number
          user_id: string
        }
        Update: {
          created_at?: string
          party_id?: number
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "party_admin_party_id_fkey"
            columns: ["party_id"]
            isOneToOne: false
            referencedRelation: "party"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "party_admin_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profile"
            referencedColumns: ["id"]
          },
        ]
      }
      performance: {
        Row: {
          created_at: string
          id: number
          key: string | null
          order: number | null
          party: number | null
          ref_link: string | null
          song: number | null
          suggested_by: string | null
        }
        Insert: {
          created_at?: string
          id?: number
          key?: string | null
          order?: number | null
          party?: number | null
          ref_link?: string | null
          song?: number | null
          suggested_by?: string | null
        }
        Update: {
          created_at?: string
          id?: number
          key?: string | null
          order?: number | null
          party?: number | null
          ref_link?: string | null
          song?: number | null
          suggested_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "performance_party_fkey"
            columns: ["party"]
            isOneToOne: false
            referencedRelation: "party"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "performance_song_fkey"
            columns: ["song"]
            isOneToOne: false
            referencedRelation: "song"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "performance_suggested_by_fkey"
            columns: ["suggested_by"]
            isOneToOne: false
            referencedRelation: "profile"
            referencedColumns: ["id"]
          },
        ]
      }
      performance_user: {
        Row: {
          created_at: string
          instrument_id: number
          performance_id: number
          user_id: string
        }
        Insert: {
          created_at?: string
          instrument_id: number
          performance_id: number
          user_id: string
        }
        Update: {
          created_at?: string
          instrument_id?: number
          performance_id?: number
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "performance_user_instrument_id_fkey"
            columns: ["instrument_id"]
            isOneToOne: false
            referencedRelation: "instrument"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "performance_user_performance_id_fkey"
            columns: ["performance_id"]
            isOneToOne: false
            referencedRelation: "performance"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "performance_user_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profile"
            referencedColumns: ["id"]
          },
        ]
      }
      profile: {
        Row: {
          avatar_url: string | null
          created_at: string
          email: string | null
          id: string
          nickname: string | null
          role: number | null
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string
          email?: string | null
          id: string
          nickname?: string | null
          role?: number | null
        }
        Update: {
          avatar_url?: string | null
          created_at?: string
          email?: string | null
          id?: string
          nickname?: string | null
          role?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "user_role_fkey"
            columns: ["role"]
            isOneToOne: false
            referencedRelation: "role"
            referencedColumns: ["id"]
          },
        ]
      }
      profile_instrument: {
        Row: {
          created_at: string
          instrument_id: number
          profile_id: string
        }
        Insert: {
          created_at?: string
          instrument_id: number
          profile_id: string
        }
        Update: {
          created_at?: string
          instrument_id?: number
          profile_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "profile_instrument_instrument_id_fkey"
            columns: ["instrument_id"]
            isOneToOne: false
            referencedRelation: "instrument"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "profile_instrument_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profile"
            referencedColumns: ["id"]
          },
        ]
      }
      role: {
        Row: {
          created_at: string
          id: number
          roleName: string | null
        }
        Insert: {
          created_at?: string
          id?: number
          roleName?: string | null
        }
        Update: {
          created_at?: string
          id?: number
          roleName?: string | null
        }
        Relationships: []
      }
      song: {
        Row: {
          added_by: string | null
          artist: string | null
          created_at: string
          duration: number | null
          id: number
          ref_link: string | null
          title: string | null
        }
        Insert: {
          added_by?: string | null
          artist?: string | null
          created_at?: string
          duration?: number | null
          id?: number
          ref_link?: string | null
          title?: string | null
        }
        Update: {
          added_by?: string | null
          artist?: string | null
          created_at?: string
          duration?: number | null
          id?: number
          ref_link?: string | null
          title?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "song_added_by_fkey"
            columns: ["added_by"]
            isOneToOne: false
            referencedRelation: "profile"
            referencedColumns: ["id"]
          },
        ]
      }
      venue: {
        Row: {
          address: string | null
          allow_party: boolean
          allow_rehearsal: boolean
          contact: string | null
          contact_name: string | null
          created_at: string
          created_by: string | null
          id: number
          instagram: string | null
          name: string | null
          venue_type: number | null
          whatsapp: string | null
        }
        Insert: {
          address?: string | null
          allow_party?: boolean
          allow_rehearsal?: boolean
          contact?: string | null
          contact_name?: string | null
          created_at?: string
          created_by?: string | null
          id?: number
          instagram?: string | null
          name?: string | null
          venue_type?: number | null
          whatsapp?: string | null
        }
        Update: {
          address?: string | null
          allow_party?: boolean
          allow_rehearsal?: boolean
          contact?: string | null
          contact_name?: string | null
          created_at?: string
          created_by?: string | null
          id?: number
          instagram?: string | null
          name?: string | null
          venue_type?: number | null
          whatsapp?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "venue_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profile"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "venue_venue_type_fkey"
            columns: ["venue_type"]
            isOneToOne: false
            referencedRelation: "venue_type"
            referencedColumns: ["id"]
          },
        ]
      }
      venue_admin: {
        Row: {
          created_at: string | null
          user_id: string
          venue_id: number
        }
        Insert: {
          created_at?: string | null
          user_id: string
          venue_id: number
        }
        Update: {
          created_at?: string | null
          user_id?: string
          venue_id?: number
        }
        Relationships: [
          {
            foreignKeyName: "venue_admin_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profile"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "venue_admin_venue_id_fkey"
            columns: ["venue_id"]
            isOneToOne: false
            referencedRelation: "venue"
            referencedColumns: ["id"]
          },
        ]
      }
      venue_type: {
        Row: {
          created_at: string
          description: string
          id: number
          name: string
        }
        Insert: {
          created_at?: string
          description: string
          id?: number
          name: string
        }
        Update: {
          created_at?: string
          description?: string
          id?: number
          name?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      can_see_party: { Args: { pid: number }; Returns: boolean }
      show_limit: { Args: never; Returns: number }
      show_trgm: { Args: { "": string }; Returns: string[] }
    }
    Enums: {
      party_status:
        | "draft"
        | "pending_venue"
        | "confirmed"
        | "live"
        | "completed"
        | "cancelled"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      party_status: [
        "draft",
        "pending_venue",
        "confirmed",
        "live",
        "completed",
        "cancelled",
      ],
    },
  },
} as const
