-- =============================================================================
-- Rock Party — Database schema (public)
-- =============================================================================
--
-- PROVENANCE
--   AUTHORITATIVE dump captured 2026-08-11 from the live Supabase project
--   (ref: ohuhilcqluniqnkxiqhr) via the SQL Editor query in
--   supabase/dump-authoritative.sql. Column names, types, nullability,
--   defaults, keys, foreign keys, unique constraints, indexes, and RLS
--   policies below all come from information_schema / pg_catalog.
--
-- CAVEATS
--   * Identity: single-column bigint PKs are written as `generated by default
--     as identity`. The dump didn't include is_identity, but this is the
--     Supabase default for such columns; adjust if any actually use a sequence.
--   * ON DELETE/UPDATE actions on FKs were not captured (assumed NO ACTION).
--   * Column position gaps in the source (e.g. party jumps pos 4->6) mean some
--     columns were dropped over the table's life; only current columns appear.
--
-- MODEL NOTES
--   * There is NO `performer` table. App "performers" are `profile` rows.
--     A performer is attached to a set-list slot via `performance_user`
--     (performance x instrument x user).
--   * Admin permissions are REAL and enforced by RLS, not just hidden in the
--     UI: `venue_admin` and `party_admin` list who may edit a venue/party.
--   * `role`, `venue_type`, `instrument` are lookup tables (all publicly
--     readable). `profile.role` and `venue.venue_type` are FKs into them.
-- =============================================================================

create extension if not exists pg_trgm;  -- for the song trigram search indexes

-- ============================ TYPES ==========================================

-- party lifecycle (see docs/specs/party-status.md)
create type public.party_status as enum
  ('draft', 'pending_venue', 'confirmed', 'live', 'completed', 'cancelled');

-- how a venue pays performers (see docs/specs/venue-profile.md, #30)
create type public.engagement_model as enum
  ('free', 'door_split', 'guarantee', 'pay_to_play', 'tips', 'bar_minimum', 'other');

-- how signups get onto a song / signup state (see docs/specs/musician-approval.md, #29)
create type public.performer_approval as enum ('auto', 'organizer', 'proponent', 'invite_only');
create type public.signup_status as enum ('pending', 'approved', 'declined');
create type public.band_role as enum ('manager', 'member');

-- ============================ LOOKUP TABLES ==================================

create table if not exists public.role (
  id         bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  "roleName" varchar
);

create table if not exists public.venue_type (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  name        text not null,
  description text not null
);

create table if not exists public.instrument (
  id         bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name       text
);

-- equipment — curated backline/PA lookup for venue profiles (#30).
create table if not exists public.equipment (
  id         bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name       text not null,
  category   text
);

-- equipment_suggestion — curated popular brand/model options per equipment type
-- (#49). Seeds the venue-equipment description autocomplete; world-readable,
-- migration-managed only. See migrations/20260824_equipment_suggestions.sql.
create table if not exists public.equipment_suggestion (
  equipment_id bigint not null references public.equipment (id) on delete cascade,
  label        text   not null,
  primary key (equipment_id, label)
);
create index if not exists idx_equipment_suggestion_equipment on public.equipment_suggestion (equipment_id);

-- ============================ CORE ENTITIES ==================================

-- profile — app users / "performers"; PK is the Supabase auth user id.
create table if not exists public.profile (
  id         uuid primary key references auth.users (id) on delete cascade,
  created_at timestamptz not null default now(),
  nickname   varchar,
  role       bigint default '3'::bigint references public.role (id),
  avatar_url text,
  email      text,
  constraint user_auth_id_key unique (id)   -- legacy unique, redundant with PK
);

-- venue — places where gigs ("toques") happen.
create table if not exists public.venue (
  id              bigint generated by default as identity primary key,
  created_at      timestamptz not null default now(),
  name            varchar,
  address         varchar,
  contact_name    varchar,
  contact         varchar,            -- free-form handle, e.g. "@acturo"
  venue_type      bigint references public.venue_type (id),
  allow_party     boolean not null default true,
  allow_rehearsal boolean not null default false,
  created_by      uuid references public.profile (id),
  whatsapp        text,               -- added via the venue_contact branch
  instagram       text,               -- added via the venue_contact branch
  -- venue profile (#30, see docs/specs/venue-profile.md)
  requires_approval boolean not null default true,
  engagement_model  public.engagement_model,
  engagement_notes  text,
  min_age           smallint,         -- 0 = all ages; null = unspecified
  curfew            time,             -- music-off time
  capacity          integer,
  house_rules       text,
  is_test           boolean not null default false  -- test data, dev-only (#67)
);

-- venue_admin — who may administer a venue (besides its creator).
-- NOTE: created_at is timestamp WITHOUT time zone (inconsistent with the other
-- tables' timestamptz). PK + user_id NOT NULL added 2026-08-11 (advisor fix).
create table if not exists public.venue_admin (
  venue_id   bigint not null references public.venue (id),
  created_at timestamp default now(),
  user_id    uuid not null references public.profile (id),
  primary key (venue_id, user_id)
);

-- party — a gig ("toque") at a venue on a date.
-- status lifecycle (see docs/specs/party-status.md): draft -> pending_venue ->
-- confirmed -> live -> completed, plus cancelled. status is the source of truth
-- approvals / live mode / discovery read from; approved_by_venue is superseded.
create table if not exists public.party (
  id                bigint generated by default as identity primary key,
  created_at        timestamptz not null default now(),
  date              date,
  venue             bigint references public.venue (id),
  title             text,
  description       text,
  approved_by_venue boolean not null default false,
  created_by        uuid references public.profile (id),
  status            public.party_status not null default 'draft',
  status_changed_at timestamptz not null default now(),
  cancel_reason     text,           -- coded: 'venue_declined' / 'organizer'
  cancel_note       text,           -- optional free-text reason (shown to organizer)
  performer_approval public.performer_approval not null default 'auto',  -- who approves players (#29)
  is_test           boolean not null default false  -- test data, dev-only (#67)
);

-- party_admin — who may administer a party (besides its creator).
create table if not exists public.party_admin (
  party_id   bigint not null references public.party (id),
  created_at timestamptz not null default now(),
  user_id    uuid not null references public.profile (id),
  primary key (party_id, user_id)
);

-- song — tracks; MusicBrainz-sourced, linked to Spotify.
create table if not exists public.song (
  id         bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  title      varchar,
  artist     varchar,
  added_by   uuid references public.profile (id),
  duration   real default '3'::real,
  ref_link   text,
  constraint song_ref_link_key unique (ref_link),
  constraint unique_song_artist unique (title, artist)
);

create index if not exists idx_song_title_trgm  on public.song using gin (title  gin_trgm_ops);
create index if not exists idx_song_artist_trgm on public.song using gin (artist gin_trgm_ops);

-- performance — a song slotted into a party's set list (drag-orderable).
create table if not exists public.performance (
  id           bigint generated by default as identity primary key,
  created_at   timestamptz not null default now(),
  party        bigint references public.party (id),
  song         bigint references public.song (id),
  ref_link     varchar,
  key          varchar,             -- musical key
  "order"      smallint,            -- set-list position (reserved word — quoted)
  suggested_by uuid references public.profile (id)
  -- band_id added by ALTER below (band table defined later) — #40
);

-- performance_user — a performer (user) playing an instrument in a performance.
create table if not exists public.performance_user (
  performance_id bigint not null references public.performance (id),
  created_at     timestamptz not null default now(),
  instrument_id  bigint not null references public.instrument (id),
  user_id        uuid   not null references public.profile (id),
  status         public.signup_status not null default 'approved',  -- trigger-owned (#29)
  -- band_id added by ALTER below (band table defined later) — #40
  primary key (performance_id, instrument_id, user_id)
);

-- profile_instrument — the instruments a performer plays (profile-level, not
-- per-song). Junction of profile × instrument. Owner-managed via RLS.
create table if not exists public.profile_instrument (
  profile_id    uuid   not null references public.profile (id) on delete cascade,
  instrument_id bigint not null references public.instrument (id),
  created_at    timestamptz not null default now(),
  primary key (profile_id, instrument_id)
);

-- venue_equipment — the equipment a venue has (venue × equipment). Managed by
-- the venue's creator or admins (#30).
create table if not exists public.venue_equipment (
  venue_id     bigint not null references public.venue (id) on delete cascade,
  equipment_id bigint not null references public.equipment (id),
  quantity     integer,   -- e.g. 4 microphones; null = unspecified
  notes        text,      -- description: brand / model / size specifics
  created_at   timestamptz not null default now(),
  primary key (venue_id, equipment_id)
);

-- notification — in-app notifications inbox (#57). Rows are created only by
-- SECURITY DEFINER triggers on real events (see notify_party_status); recipients
-- read / mark-read / delete their own. See migrations/20260825_notifications.sql.
create table if not exists public.notification (
  id         bigint generated by default as identity primary key,
  recipient  uuid  not null references public.profile (id) on delete cascade,
  type       text  not null,
  payload    jsonb not null default '{}'::jsonb,
  read_at    timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists idx_notification_recipient on public.notification (recipient, created_at desc);
create index if not exists idx_notification_unread     on public.notification (recipient) where read_at is null;

-- party_rsvp — a user marks they're attending a toque (#58). A row = going;
-- owner-managed, attendance public. See migrations/20260825_party_rsvp.sql.
create table if not exists public.party_rsvp (
  party_id   bigint not null references public.party (id) on delete cascade,
  user_id    uuid   not null references public.profile (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (party_id, user_id)
);
create index if not exists idx_party_rsvp_user on public.party_rsvp (user_id);

-- dev_user — developer accounts (#67). Members see test data (party/venue with
-- is_test = true). NO insert/update/delete policy, so a user cannot self-escalate;
-- dev is granted only out-of-band (SQL editor / service_role). See
-- migrations/20260827_test_data_visibility.sql.
create table if not exists public.dev_user (
  user_id    uuid primary key references auth.users (id) on delete cascade,
  created_at timestamptz not null default now()
);

-- ---- bands (#40) ------------------------------------------------------------
-- A persistent band: a musician can be in many; managers vs members; instruments
-- are per-band (not the global profile_instrument list). See docs/specs/bands.md.
create table if not exists public.band (
  id              bigint generated by default as identity primary key,
  created_at      timestamptz not null default now(),
  name            text not null,
  bio             text,
  avatar_url      text,                                   -- Storage upload (#75)
  who_can_sign_up text not null default 'members'
                  check (who_can_sign_up in ('members', 'managers')),
  created_by      uuid references public.profile (id),
  is_test         boolean not null default false            -- test data, dev-only (#76)
);
create table if not exists public.band_member (
  band_id    bigint not null references public.band (id) on delete cascade,
  user_id    uuid   not null references public.profile (id) on delete cascade,
  role       public.band_role not null default 'member',
  created_at timestamptz not null default now(),
  primary key (band_id, user_id)
);
create table if not exists public.band_member_instrument (
  band_id       bigint not null,
  user_id       uuid   not null,
  instrument_id bigint not null references public.instrument (id),
  created_at    timestamptz not null default now(),
  primary key (band_id, user_id, instrument_id),
  foreign key (band_id, user_id)
    references public.band_member (band_id, user_id) on delete cascade
);
-- Band links onto the setlist (band table now exists — see reverted columns above).
alter table public.performance      add column if not exists band_id bigint references public.band (id);
alter table public.performance_user add column if not exists band_id bigint references public.band (id);

-- ---- foreign-key covering indexes (advisor fix 2026-08-11) ------------------
-- venue_admin.venue_id is covered by its composite PK, so it's omitted here.
create index if not exists idx_party_created_by            on public.party (created_by);
create index if not exists idx_party_venue                 on public.party (venue);
create index if not exists idx_party_admin_user_id         on public.party_admin (user_id);
create index if not exists idx_performance_party           on public.performance (party);
create index if not exists idx_performance_song            on public.performance (song);
create index if not exists idx_performance_suggested_by    on public.performance (suggested_by);
create index if not exists idx_performance_user_instrument on public.performance_user (instrument_id);
create index if not exists idx_performance_user_user_id    on public.performance_user (user_id);
create index if not exists idx_profile_instrument_instrument on public.profile_instrument (instrument_id);
create index if not exists idx_venue_equipment_equipment on public.venue_equipment (equipment_id);
create index if not exists idx_profile_role                on public.profile (role);
create index if not exists idx_song_added_by               on public.song (added_by);
create index if not exists idx_venue_created_by            on public.venue (created_by);
create index if not exists idx_venue_venue_type            on public.venue (venue_type);
create index if not exists idx_venue_admin_user_id         on public.venue_admin (user_id);
create index if not exists idx_band_created_by             on public.band (created_by);
create index if not exists idx_band_member_user            on public.band_member (user_id);
create index if not exists idx_bmi_instrument              on public.band_member_instrument (instrument_id);
create index if not exists idx_performance_band            on public.performance (band_id);
create index if not exists idx_performance_user_band       on public.performance_user (band_id);

-- =============================================================================
-- FUNCTIONS & TRIGGERS
-- =============================================================================
-- can_see_party: party visibility used by the performance SELECT policy.
-- SECURITY INVOKER — runs as the caller and leans on party's own SELECT policy
-- for the visibility rule (single source of truth; no public security-definer
-- RPC to worry about). No recursion: party's policy doesn't reference performance.
create or replace function public.can_see_party(pid bigint)
returns boolean language sql stable security invoker set search_path = '' as $$
  select exists (select 1 from public.party p where p.id = pid);
$$;

-- can_see_band: band visibility (#76), used by the band_member / _instrument
-- SELECT policies. SECURITY INVOKER — leans on band's own SELECT policy. No
-- recursion: band's policy references only is_test and is_dev(), not band_member.
create or replace function public.can_see_band(bid bigint)
returns boolean language sql stable security invoker set search_path = '' as $$
  select exists (select 1 from public.band b where b.id = bid);
$$;

-- is_dev: true when the caller is a developer (#67). SECURITY DEFINER so it can
-- read dev_user regardless of that table's RLS. Used by the party/venue SELECT
-- policies to reveal test data to devs.
create or replace function public.is_dev()
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (select 1 from public.dev_user d where d.user_id = (select auth.uid()));
$$;

-- Bands (#40). SECURITY DEFINER so they read band_member without RLS recursion.
create or replace function public.is_band_manager(bid bigint)
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.band_member bm
    where bm.band_id = bid and bm.user_id = (select auth.uid()) and bm.role = 'manager'
  );
$$;
create or replace function public.can_sign_up_band(bid bigint)
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.band b
    join public.band_member bm on bm.band_id = b.id
    where b.id = bid and bm.user_id = (select auth.uid())
      and (b.who_can_sign_up = 'members' or bm.role = 'manager')
  );
$$;
-- creator becomes the first manager (mirrors party.auto_add_admin)
create or replace function public.add_band_creator_as_manager()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  if new.created_by is not null then
    insert into public.band_member (band_id, user_id, role)
    values (new.id, new.created_by, 'manager')
    on conflict (band_id, user_id) do nothing;
  end if;
  return new;
end;
$$;
drop trigger if exists band_add_creator_manager on public.band;
create trigger band_add_creator_manager
  after insert on public.band
  for each row execute function public.add_band_creator_as_manager();
-- sign a band up to a song: SECURITY DEFINER (inserts rows for other members,
-- which the "insert self" signup policy forbids); status set by the existing
-- performance_user_set_status trigger per the toque's approval mode. Emits ONE
-- 'band_signup_requested' notification when the band's rows land pending (#73),
-- and blocks a test band from signing up for a real event (#76 follow-up).
create or replace function public.sign_band_up(p_performance bigint, p_band bigint)
returns void language plpgsql security definer set search_path = '' as $$
declare
  v_party bigint; v_party_title text; v_song_title text; v_band_name text;
  v_uid uuid := (select auth.uid());
begin
  if not public.can_sign_up_band(p_band) then
    raise exception 'not allowed to sign up this band';
  end if;

  -- A test band may not play a real event (would leak its lineup on a public
  -- setlist). The reverse — a real band on a test toque — is fine (#76).
  if exists (
    select 1 from public.band b
    join public.performance perf on perf.id = p_performance
    join public.party pt on pt.id = perf.party
    where b.id = p_band and b.is_test = true and pt.is_test = false
  ) then
    raise exception 'a test band cannot sign up for a real event';
  end if;

  update public.performance
    set band_id = p_band
    where id = p_performance and (band_id is null or band_id = p_band);
  if not found then
    raise exception 'song not available for this band';
  end if;

  insert into public.performance_user (performance_id, user_id, instrument_id, band_id)
  select p_performance, bmi.user_id, bmi.instrument_id, p_band
  from public.band_member_instrument bmi
  where bmi.band_id = p_band
  on conflict (performance_id, instrument_id, user_id) do nothing;

  select perf.party, pt.title, s.title, b.name
    into v_party, v_party_title, v_song_title, v_band_name
  from public.performance perf
  join public.party pt on pt.id = perf.party
  left join public.song s on s.id = perf.song
  join public.band b on b.id = p_band
  where perf.id = p_performance;

  if exists (
    select 1 from public.performance_user pu
    where pu.performance_id = p_performance and pu.band_id = p_band and pu.status = 'pending'
  ) then
    insert into public.notification (recipient, type, payload)
    select r.uid, 'band_signup_requested',
           jsonb_build_object('party_id', v_party, 'party_title', v_party_title,
                              'band_id', p_band, 'band_name', v_band_name,
                              'song_title', v_song_title, 'performance_id', p_performance)
    from (
      select pt.created_by as uid from public.party pt where pt.id = v_party and pt.created_by is not null
      union
      select pa.user_id from public.party_admin pa where pa.party_id = v_party
    ) r
    where r.uid is not null and r.uid <> v_uid;
  end if;
end; $$;

-- approve/decline a band signup as a UNIT (#74): flips all the band's pending
-- performance_user rows together + one notification to the signer. SECURITY
-- DEFINER (notify_signup skips band rows; clients can't insert notifications).
-- Authorizes the caller like set_signup_status; the BEFORE-UPDATE trigger
-- re-checks too. Decline keeps rows ('declined'); the setlist hides a fully
-- declined band song.
create or replace function public.set_band_signup_status(
  p_performance bigint, p_band bigint, p_status public.signup_status
) returns void language plpgsql security definer set search_path = '' as $$
declare
  v_party bigint; v_party_title text; v_song_title text; v_band_name text;
  v_signer uuid; v_mode public.performer_approval;
  v_uid uuid := (select auth.uid());
  v_n int;
begin
  if p_status not in ('approved', 'declined') then
    raise exception 'invalid status';
  end if;

  select perf.party, pt.title, s.title, b.name, perf.suggested_by, pt.performer_approval
    into v_party, v_party_title, v_song_title, v_band_name, v_signer, v_mode
  from public.performance perf
  join public.party pt on pt.id = perf.party
  left join public.song s on s.id = perf.song
  join public.band b on b.id = p_band
  where perf.id = p_performance and perf.band_id = p_band;
  if not found then
    raise exception 'band is not signed up for this song';
  end if;

  if not (
       exists (select 1 from public.party pt where pt.id = v_party and pt.created_by = v_uid)
    or exists (select 1 from public.party_admin pa where pa.party_id = v_party and pa.user_id = v_uid)
    or (v_mode = 'proponent' and v_signer = v_uid)
  ) then
    raise exception 'not allowed to decide this signup';
  end if;

  update public.performance_user
    set status = p_status
    where performance_id = p_performance and band_id = p_band and status = 'pending';
  get diagnostics v_n = row_count;
  if v_n = 0 then
    return;
  end if;

  if v_signer is not null and v_signer <> v_uid then
    insert into public.notification (recipient, type, payload)
    values (v_signer,
            case when p_status = 'approved' then 'band_signup_approved' else 'band_signup_declined' end,
            jsonb_build_object('party_id', v_party, 'party_title', v_party_title,
                               'band_id', p_band, 'band_name', v_band_name,
                               'song_title', v_song_title, 'performance_id', p_performance));
  end if;
end; $$;

-- keep party.status_changed_at fresh on status transitions
create or replace function public.set_status_changed_at()
returns trigger language plpgsql set search_path = '' as $$
begin
  if new.status is distinct from old.status then
    new.status_changed_at = now();
  end if;
  return new;
end;
$$;

create trigger party_status_changed
  before update on public.party
  for each row execute function public.set_status_changed_at();

-- (public.auto_add_admin also exists: a trigger that auto-adds a party's
--  creator as a party_admin on insert.)

-- performance_user.status is trigger-owned (not client-writable) — #29.
-- INSERT: approved if mode is 'auto', or the inserter is a party admin, or (in
-- proponent mode) the song's proponent; invite_only rejects a non-admin/proponent
-- self-signup; otherwise pending. UPDATE: only admins (or the proponent, in
-- proponent mode) may change status. security invoker: lookups run under the
-- acting user's RLS (a toque they can act on is one they can see).
create or replace function public.set_signup_status()
returns trigger language plpgsql security invoker set search_path = '' as $$
declare
  v_party bigint; v_mode public.performer_approval; v_proponent uuid;
  v_is_admin boolean; v_is_prop boolean;
begin
  select perf.party, pt.performer_approval, perf.suggested_by
    into v_party, v_mode, v_proponent
  from public.performance perf join public.party pt on pt.id = perf.party
  where perf.id = new.performance_id;

  v_is_admin :=
    exists (select 1 from public.party pt where pt.id = v_party and pt.created_by = auth.uid())
    or exists (select 1 from public.party_admin pa where pa.party_id = v_party and pa.user_id = auth.uid());
  v_is_prop := (v_proponent is not null and v_proponent = auth.uid());

  if tg_op = 'INSERT' then
    if v_mode = 'invite_only' and not (v_is_admin or v_is_prop) then
      raise exception 'Las inscripciones a este toque son solo por invitación';
    end if;
    if v_mode = 'auto' or v_is_admin or (v_mode = 'proponent' and v_is_prop) then
      new.status := 'approved';
    else
      new.status := 'pending';
    end if;
    return new;
  elsif tg_op = 'UPDATE' then
    if new.status is distinct from old.status
       and not (v_is_admin or (v_mode = 'proponent' and v_is_prop)) then
      raise exception 'No puedes cambiar el estado de esta inscripción';
    end if;
    return new;
  end if;
  return new;
end;
$$;

create trigger performance_user_set_status
  before insert or update on public.performance_user
  for each row execute function public.set_signup_status();

-- notify_signup (#65): notifications on signup events — a pending request pings
-- the approvers (party admins + proponent in proponent mode); approve/decline
-- pings the applicant. AFTER trigger; recipient is never the actor. Band-tagged
-- rows are skipped — bands notify once from sign_band_up / the approval RPC (#73).
-- See migrations/20260826_signup_notifications.sql + 20260902_band_signup_notify.sql.
create or replace function public.notify_signup()
returns trigger language plpgsql security definer set search_path = '' as $$
declare
  v_party bigint; v_party_title text; v_song_title text;
  v_mode public.performer_approval; v_proponent uuid;
begin
  if new.band_id is not null then
    return new;                              -- bands notify once (sign_band_up / approval RPC)
  end if;

  select perf.party, pt.title, s.title, pt.performer_approval, perf.suggested_by
    into v_party, v_party_title, v_song_title, v_mode, v_proponent
  from public.performance perf
  join public.party pt on pt.id = perf.party
  left join public.song s on s.id = perf.song
  where perf.id = new.performance_id;

  if tg_op = 'INSERT' and new.status = 'pending' then
    insert into public.notification (recipient, type, payload)
    select r.uid, 'signup_requested',
           jsonb_build_object('party_id', v_party, 'party_title', v_party_title,
                              'song_title', v_song_title, 'performance_id', new.performance_id)
    from (
      select pt.created_by as uid from public.party pt where pt.id = v_party and pt.created_by is not null
      union
      select pa.user_id from public.party_admin pa where pa.party_id = v_party
      union
      select v_proponent where v_mode = 'proponent' and v_proponent is not null
    ) r
    where r.uid is not null and r.uid <> new.user_id;
  elsif tg_op = 'UPDATE' and new.status is distinct from old.status and old.status = 'pending' then
    if new.status = 'approved' then
      insert into public.notification (recipient, type, payload)
      values (new.user_id, 'signup_approved',
              jsonb_build_object('party_id', v_party, 'party_title', v_party_title,
                                 'song_title', v_song_title, 'performance_id', new.performance_id));
    elsif new.status = 'declined' then
      insert into public.notification (recipient, type, payload)
      values (new.user_id, 'signup_declined',
              jsonb_build_object('party_id', v_party, 'party_title', v_party_title,
                                 'song_title', v_song_title, 'performance_id', new.performance_id));
    end if;
  end if;
  return new;
end; $$;

drop trigger if exists performance_user_notify on public.performance_user;
create trigger performance_user_notify
  after insert or update on public.performance_user
  for each row execute function public.notify_signup();

-- notify_party_status (#57): create in-app notifications on party status
-- transitions. SECURITY DEFINER so it can insert rows for other recipients
-- (the notification table has no client INSERT policy). See the migration for
-- the full body; #51 extends the producers (live, reminders, signups).
create or replace function public.notify_party_status()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  if new.status is distinct from old.status then
    if new.status = 'confirmed' and old.status = 'pending_venue' and new.created_by is not null then
      insert into public.notification (recipient, type, payload)
      values (new.created_by, 'party_approved',
              jsonb_build_object('party_id', new.id, 'party_title', new.title));
    elsif new.status = 'cancelled'
      and new.cancel_reason in ('venue_declined', 'venue_cancelled')
      and new.created_by is not null then
      insert into public.notification (recipient, type, payload)
      values (new.created_by,
              case when new.cancel_reason = 'venue_declined'
                   then 'party_declined' else 'party_venue_cancelled' end,
              jsonb_build_object('party_id', new.id, 'party_title', new.title, 'reason', new.cancel_note));
    elsif new.status = 'pending_venue' then
      insert into public.notification (recipient, type, payload)
      select uid, 'party_pending_venue',
             jsonb_build_object('party_id', new.id, 'party_title', new.title)
      from (
        select v.created_by as uid from public.venue v
          where v.id = new.venue and v.created_by is not null
        union
        select va.user_id from public.venue_admin va where va.venue_id = new.venue
      ) recips;
    elsif new.status = 'live' then
      insert into public.notification (recipient, type, payload)
      select distinct pu.user_id, 'party_live',
             jsonb_build_object('party_id', new.id, 'party_title', new.title)
      from public.performance perf
      join public.performance_user pu on pu.performance_id = perf.id
      where perf.party = new.id and pu.status = 'approved';
    end if;
  end if;
  return new;
end; $$;

drop trigger if exists party_status_notify on public.party;
create trigger party_status_notify
  after update on public.party
  for each row execute function public.notify_party_status();

-- notify_upcoming_toques (#51): day-before reminder for confirmed toques →
-- organizer + approved performers. Scheduled daily via pg_cron (job
-- 'daily-toque-reminders'); see migrations/20260825_notification_producers.sql.
create or replace function public.notify_upcoming_toques()
returns void language plpgsql security definer set search_path = '' as $$
begin
  insert into public.notification (recipient, type, payload)
  select r.uid, 'party_reminder',
         jsonb_build_object('party_id', p.id, 'party_title', p.title, 'date', p.date)
  from public.party p
  join lateral (
    select p.created_by as uid where p.created_by is not null
    union
    select pu.user_id
    from public.performance perf
    join public.performance_user pu on pu.performance_id = perf.id
    where perf.party = p.id and pu.status = 'approved'
  ) r on true
  where p.status = 'confirmed'
    and p.date = (current_date + 1)
    and not exists (
      select 1 from public.notification n
      where n.recipient = r.uid and n.type = 'party_reminder'
        and (n.payload ->> 'party_id')::bigint = p.id
    );
end; $$;
revoke execute on function public.notify_upcoming_toques() from public;

-- =============================================================================
-- ROW LEVEL SECURITY
-- =============================================================================
-- RLS is ENABLED on every table. General pattern:
--   * SELECT: open to anon + authenticated (public read app), EXCEPT party and
--     performance, which are gated by party status/visibility (drafts, pending,
--     and cancelled toques + their setlists are hidden from the public — see
--     the party/performance policies and can_see_party()).
--   * INSERT: any authenticated user.
--   * UPDATE/DELETE: restricted to owners/admins via *_admin tables.
--
-- SECURITY NOTES worth reviewing (Epic 2):
--   * performance UPDATE is restricted to the parent party's owner/admins, and
--     performance_user UPDATE to the owning user (tightened 2026-08-11; see
--     migrations/20260811_tighten_performance_update_rls.sql). INSERT remains
--     open to any authenticated user by design (collaborative suggestions).
--   * Core tables party, venue, song, profile have NO DELETE policy, so with
--     RLS on, deletes are denied to anon/authenticated. `performance` is the
--     exception: it has a DELETE policy scoped to party owner/admins (#62), so a
--     song can be removed from a setlist.
--   * The lookup tables `role`, `venue_type`, `instrument` are publicly
--     readable (SELECT to all). No table is deny-all anymore.
--   * auth.uid() is wrapped as (select auth.uid()) in the owner/admin policies
--     so it's evaluated once per query, not per row (advisor fix 2026-08-11;
--     see migrations/20260811_advisor_fixes.sql).
-- =============================================================================

alter table public.role              enable row level security;
alter table public.venue_type        enable row level security;
alter table public.instrument        enable row level security;
alter table public.profile           enable row level security;
alter table public.venue             enable row level security;
alter table public.venue_admin       enable row level security;
alter table public.party             enable row level security;
alter table public.party_admin       enable row level security;
alter table public.song              enable row level security;
alter table public.performance       enable row level security;
alter table public.performance_user  enable row level security;
alter table public.profile_instrument enable row level security;
alter table public.equipment          enable row level security;
alter table public.equipment_suggestion enable row level security;
alter table public.venue_equipment    enable row level security;
alter table public.notification       enable row level security;
alter table public.party_rsvp         enable row level security;
alter table public.dev_user           enable row level security;
alter table public.band                   enable row level security;
alter table public.band_member            enable row level security;
alter table public.band_member_instrument enable row level security;

-- ---- song -------------------------------------------------------------------
create policy "allow select to all users" on public.song
  for select to anon, authenticated using (true);
create policy "allow insert to authenticated users" on public.song
  for insert to authenticated with check (true);

-- ---- venue ------------------------------------------------------------------
-- Test venues (#67) are hidden from everyone except devs.
create policy "allow select to all users" on public.venue
  for select to anon, authenticated using (is_test = false or public.is_dev());
create policy "allow insert to authenticated users" on public.venue
  for insert to authenticated with check (true);
create policy "allow update to venue admins" on public.venue
  for update using (
    (created_by = (select auth.uid()))
    or exists (
      select 1 from public.venue_admin
      where venue_admin.venue_id = venue.id and venue_admin.user_id = (select auth.uid())
    )
  );

-- ---- venue_admin ------------------------------------------------------------
create policy "Enable read access for all users" on public.venue_admin
  for select to anon, authenticated using (true);
create policy "allow insert for party admins" on public.venue_admin
  for insert to authenticated with check (
    ((select venue.created_by from public.venue where venue.id = venue_admin.venue_id) = (select auth.uid()))
    or exists (
      select 1 from public.venue_admin venue_admin_1
      where venue_admin_1.venue_id = venue_admin.venue_id and venue_admin_1.user_id = (select auth.uid())
    )
  );
create policy "allow delete for venue admins" on public.venue_admin
  for delete to authenticated using (
    ((select auth.uid()) = user_id)
    or exists (
      select 1 from public.venue_admin venue_admin_1
      where venue_admin_1.venue_id = venue_admin.venue_id and venue_admin_1.user_id = auth.uid()
    )
  );

-- ---- party ------------------------------------------------------------------
-- Public statuses are world-readable; drafts/pending/cancelled only to the
-- owner, party admins, or the venue's owner/admins (see docs/specs/party-status.md).
-- The venue OWNER is checked explicitly because venue creators aren't in venue_admin.
-- Test toques (#67) are additionally hidden from everyone except devs.
create policy "select party: public statuses or owner/admins" on public.party
  for select to anon, authenticated
  using (
    (
      status in ('confirmed', 'live', 'completed')
      or created_by = (select auth.uid())
      or exists (select 1 from public.party_admin pa
                 where pa.party_id = party.id and pa.user_id = (select auth.uid()))
      or exists (select 1 from public.venue v
                 where v.id = party.venue and v.created_by = (select auth.uid()))
      or exists (select 1 from public.venue_admin va
                 where va.venue_id = party.venue and va.user_id = (select auth.uid()))
    )
    and (is_test = false or public.is_dev())
  );
create policy "allow insert to authenticated users" on public.party
  for insert to authenticated with check (true);
-- Creator, party admins, OR the venue's owner/admins (the last two so a venue's
-- people can approve/decline a pending_venue toque — #31). The venue OWNER is
-- checked explicitly because venue creators aren't auto-added to venue_admin.
create policy "allow update to party admins" on public.party
  for update to authenticated using (
    (created_by = (select auth.uid()))
    or exists (
      select 1 from public.party_admin
      where party_admin.party_id = party.id and party_admin.user_id = (select auth.uid())
    )
    or exists (
      select 1 from public.venue v
      where v.id = party.venue and v.created_by = (select auth.uid())
    )
    or exists (
      select 1 from public.venue_admin
      where venue_admin.venue_id = party.venue and venue_admin.user_id = (select auth.uid())
    )
  ) with check (true);

-- ---- party_admin ------------------------------------------------------------
create policy "Enable read access for authenticated users" on public.party_admin
  for select to authenticated using (true);
create policy "allow Insert to party owner and other party admins" on public.party_admin
  for insert to authenticated with check (
    ((select party.created_by from public.party where party.id = party_admin.party_id) = (select auth.uid()))
    or exists (
      select 1 from public.party_admin party_admin_1
      where party_admin_1.party_id = party_admin.party_id and party_admin_1.user_id = (select auth.uid())
    )
  );
create policy "Enable delete for party admins" on public.party_admin
  for delete to authenticated using (
    ((select auth.uid()) = user_id)
    or exists (
      select 1 from public.party_admin party_admin_1
      where party_admin_1.party_id = party_admin.party_id and party_admin_1.user_id = auth.uid()
    )
  );

-- ---- performance ------------------------------------------------------------
-- A hidden party's setlist stays hidden (gated by parent-party visibility).
create policy "select performance: parent party visible" on public.performance
  for select to anon, authenticated
  using (public.can_see_party(performance.party));
create policy "allow insert to authenticated users" on public.performance
  for insert to authenticated with check (true);
create policy "Enable Update for authenticated users only" on public.performance
  for update to authenticated using (
    exists (
      select 1 from public.party p
      where p.id = performance.party
        and (
          p.created_by = (select auth.uid())
          or exists (
            select 1 from public.party_admin pa
            where pa.party_id = p.id and pa.user_id = (select auth.uid())
          )
        )
    )
  );
-- Remove a song from a setlist (#62): same scope as UPDATE — party creator or
-- admin. Cascades to performance_user (FK ON DELETE CASCADE).
create policy "delete performance: party admins" on public.performance
  for delete to authenticated using (
    exists (
      select 1 from public.party p
      where p.id = performance.party
        and (
          p.created_by = (select auth.uid())
          or exists (
            select 1 from public.party_admin pa
            where pa.party_id = p.id and pa.user_id = (select auth.uid())
          )
        )
    )
  );

-- ---- performance_user -------------------------------------------------------
-- Signups (#29): approved rows are public; pending/declined only to the row's
-- user and the toque's approvers (creator/admins, or the song's proponent in
-- proponent mode). Same predicate gates INSERT/UPDATE/DELETE (self OR approver);
-- the invite_only guard + status ownership live in the set_signup_status trigger.
create policy "signup select: approved public, else owner/approvers" on public.performance_user
  for select to anon, authenticated using (
    status = 'approved'
    or user_id = (select auth.uid())
    or exists (
      select 1 from public.performance perf join public.party pt on pt.id = perf.party
      where perf.id = performance_user.performance_id and (
        pt.created_by = (select auth.uid())
        or exists (select 1 from public.party_admin pa where pa.party_id = pt.id and pa.user_id = (select auth.uid()))
        or (pt.performer_approval = 'proponent' and perf.suggested_by = (select auth.uid()))
      )
    )
  );
-- Band-owned songs are not open jams (#74 follow-up): no direct client signup to
-- a band-owned performance, and band-tagged rows are managed only by the definer
-- RPCs (sign_band_up / set_band_signup_status) + FK cascades — never row-by-row.
create policy "signup insert: self, admin, or proponent" on public.performance_user
  for insert to authenticated with check (
    (select perf.band_id from public.performance perf where perf.id = performance_user.performance_id) is null
    and (
      user_id = (select auth.uid())
      or exists (
        select 1 from public.performance perf join public.party pt on pt.id = perf.party
        where perf.id = performance_user.performance_id and (
          pt.created_by = (select auth.uid())
          or exists (select 1 from public.party_admin pa where pa.party_id = pt.id and pa.user_id = (select auth.uid()))
          or (pt.performer_approval = 'proponent' and perf.suggested_by = (select auth.uid()))
        )
      )
    )
  );
create policy "signup update: self, admin, or proponent" on public.performance_user
  for update to authenticated using (
    band_id is null
    and (
      user_id = (select auth.uid())
      or exists (
        select 1 from public.performance perf join public.party pt on pt.id = perf.party
        where perf.id = performance_user.performance_id and (
          pt.created_by = (select auth.uid())
          or exists (select 1 from public.party_admin pa where pa.party_id = pt.id and pa.user_id = (select auth.uid()))
          or (pt.performer_approval = 'proponent' and perf.suggested_by = (select auth.uid()))
        )
      )
    )
  );
create policy "signup delete: self, admin, or proponent" on public.performance_user
  for delete to authenticated using (
    band_id is null
    and (
      user_id = (select auth.uid())
      or exists (
        select 1 from public.performance perf join public.party pt on pt.id = perf.party
        where perf.id = performance_user.performance_id and (
          pt.created_by = (select auth.uid())
          or exists (select 1 from public.party_admin pa where pa.party_id = pt.id and pa.user_id = (select auth.uid()))
          or (pt.performer_approval = 'proponent' and perf.suggested_by = (select auth.uid()))
        )
      )
    )
  );

-- ---- profile_instrument -----------------------------------------------------
-- Readable by all; a performer manages only their own rows. No UPDATE policy
-- (add/remove only), so updates stay denied.
create policy "allow select to all users" on public.profile_instrument
  for select to anon, authenticated using (true);
create policy "allow insert to own profile" on public.profile_instrument
  for insert to authenticated with check (profile_id = (select auth.uid()));
create policy "allow delete to own profile" on public.profile_instrument
  for delete to authenticated using (profile_id = (select auth.uid()));

-- ---- profile ----------------------------------------------------------------
-- Rows are world-readable, BUT the `email` column is hidden from client SELECT
-- (see migrations/20260821_profile_email_privacy.sql): table-level SELECT is
-- revoked and re-granted per-column for everything except email. Nothing reads
-- another user's email; the current user's comes from the auth session. Writes
-- are unaffected.
create policy "allow select to all users" on public.profile
  for select to anon, authenticated using (true);
create policy "allow insert to authenticated users" on public.profile
  for insert to authenticated with check (true);
create policy "allow update to own user" on public.profile
  for update to authenticated using (id = (select auth.uid()));
revoke select on public.profile from anon, authenticated;
grant select (id, created_at, nickname, role, avatar_url)
  on public.profile to anon, authenticated;

-- ---- instrument -------------------------------------------------------------
create policy "Enable read access for all users" on public.instrument
  for select to anon, authenticated using (true);

-- ---- equipment (public lookup) / venue_equipment ----------------------------
create policy "allow select to all users" on public.equipment
  for select to anon, authenticated using (true);
-- equipment_suggestion: world-readable curated catalog (#49), no write policy.
create policy "allow select to all users" on public.equipment_suggestion
  for select to anon, authenticated using (true);

create policy "allow select to all users" on public.venue_equipment
  for select to anon, authenticated using (true);
create policy "venue admins insert equipment" on public.venue_equipment
  for insert to authenticated with check (
    ((select venue.created_by from public.venue where venue.id = venue_equipment.venue_id) = (select auth.uid()))
    or exists (
      select 1 from public.venue_admin
      where venue_admin.venue_id = venue_equipment.venue_id
        and venue_admin.user_id = (select auth.uid())
    )
  );
create policy "venue admins delete equipment" on public.venue_equipment
  for delete to authenticated using (
    ((select venue.created_by from public.venue where venue.id = venue_equipment.venue_id) = (select auth.uid()))
    or exists (
      select 1 from public.venue_admin
      where venue_admin.venue_id = venue_equipment.venue_id
        and venue_admin.user_id = (select auth.uid())
    )
  );

-- ---- venue_type -------------------------------------------------------------
create policy "Enable read access for all users" on public.venue_type
  for select to public using (true);

-- ---- role -------------------------------------------------------------------
create policy "Enable read access for all users" on public.role
  for select to anon, authenticated using (true);

-- ---- notification -----------------------------------------------------------
-- Own-only. No INSERT policy: rows come from SECURITY DEFINER triggers (#57).
create policy "notification select own" on public.notification
  for select to authenticated using (recipient = (select auth.uid()));
create policy "notification update own" on public.notification
  for update to authenticated using (recipient = (select auth.uid()));
create policy "notification delete own" on public.notification
  for delete to authenticated using (recipient = (select auth.uid()));

-- ---- party_rsvp -------------------------------------------------------------
-- Attendance is public (counts/lists); users add/remove only their own. #58.
create policy "allow select to all users" on public.party_rsvp
  for select to anon, authenticated using (true);
create policy "rsvp insert self" on public.party_rsvp
  for insert to authenticated with check (user_id = (select auth.uid()));
create policy "rsvp delete self" on public.party_rsvp
  for delete to authenticated using (user_id = (select auth.uid()));

-- ---- dev_user ---------------------------------------------------------------
-- A user may read ONLY their own membership row (lets the client show the dev
-- toggle). No insert/update/delete policy: dev status is granted only via the
-- SQL editor / service_role, so users cannot self-escalate. #67.
create policy "dev_user self read" on public.dev_user
  for select to authenticated using (user_id = (select auth.uid()));

-- ---- bands (#40) ------------------------------------------------------------
-- Public read (discoverable); writes restricted to that band's managers. The
-- creator's manager row is added by the band_add_creator_manager trigger
-- (SECURITY DEFINER), so the insert policy only covers managers adding others.
-- Test bands (#76) are hidden from everyone except devs (mirrors party/venue).
create policy "band select visible"  on public.band for select to anon, authenticated using (is_test = false or public.is_dev());
create policy "band insert self"     on public.band for insert to authenticated with check (created_by = (select auth.uid()));
create policy "band update managers" on public.band for update to authenticated using (public.is_band_manager(id));
create policy "band delete managers" on public.band for delete to authenticated using (public.is_band_manager(id));

-- A hidden test band's roster stays hidden too (#76).
create policy "band_member select visible"        on public.band_member for select to anon, authenticated using (public.can_see_band(band_id));
create policy "band_member insert managers"      on public.band_member for insert to authenticated with check (public.is_band_manager(band_id));
create policy "band_member update managers"      on public.band_member for update to authenticated using (public.is_band_manager(band_id));
create policy "band_member delete managers/self" on public.band_member for delete to authenticated using (public.is_band_manager(band_id) or user_id = (select auth.uid()));

create policy "bmi select visible"  on public.band_member_instrument for select to anon, authenticated using (public.can_see_band(band_id));
create policy "bmi insert managers" on public.band_member_instrument for insert to authenticated with check (public.is_band_manager(band_id));
create policy "bmi update managers" on public.band_member_instrument for update to authenticated using (public.is_band_manager(band_id));
create policy "bmi delete managers" on public.band_member_instrument for delete to authenticated using (public.is_band_manager(band_id));

-- ---- band avatars (storage, #75) --------------------------------------------
-- Bucket 'band-avatars' (public read; file_size_limit 256 KB, image/webp only —
-- a server-side backstop to the client 150 KB/WebP crop). Objects live at
-- {band_id}/{timestamp}.webp; only a band's managers may write its folder.
-- Defined in migrations/20260903_band_avatars_bucket.sql (storage schema — kept
-- here for reference; storage.buckets/objects are managed by Supabase).
--   insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
--     values ('band-avatars','band-avatars', true, 262144, array['image/webp']);
--   policy "band-avatars public read"    select using (bucket_id = 'band-avatars')
--   policy "band-avatars manager insert" insert with check
--     (bucket_id = 'band-avatars' and public.is_band_manager((storage.foldername(name))[1]::bigint))
--   policy "band-avatars manager update" / "...delete" — same predicate.
