-- =============================================================================
-- Rock Party — Database schema (public)
-- =============================================================================
--
-- PROVENANCE
--   AUTHORITATIVE dump captured 2026-08-11 from the live Supabase project
--   (ref: ohuhilcqluniqnkxiqhr) via the SQL Editor query in
--   supabase/dump-authoritative.sql. Column names, types, nullability,
--   defaults, keys, foreign keys, unique constraints, indexes, and RLS
--   policies below all come from information_schema / pg_catalog.
--
-- CAVEATS
--   * Identity: single-column bigint PKs are written as `generated by default
--     as identity`. The dump didn't include is_identity, but this is the
--     Supabase default for such columns; adjust if any actually use a sequence.
--   * ON DELETE/UPDATE actions on FKs were not captured (assumed NO ACTION).
--   * Column position gaps in the source (e.g. party jumps pos 4->6) mean some
--     columns were dropped over the table's life; only current columns appear.
--
-- MODEL NOTES
--   * There is NO `performer` table. App "performers" are `profile` rows.
--     A performer is attached to a set-list slot via `performance_user`
--     (performance x instrument x user).
--   * Admin permissions are REAL and enforced by RLS, not just hidden in the
--     UI: `venue_admin` and `party_admin` list who may edit a venue/party.
--   * `role`, `venue_type`, `instrument` are lookup tables (all publicly
--     readable). `profile.role` and `venue.venue_type` are FKs into them.
-- =============================================================================

create extension if not exists pg_trgm;  -- for the song trigram search indexes

-- ============================ TYPES ==========================================

-- party lifecycle (see docs/specs/party-status.md)
create type public.party_status as enum
  ('draft', 'pending_venue', 'confirmed', 'live', 'completed', 'cancelled');

-- ============================ LOOKUP TABLES ==================================

create table if not exists public.role (
  id         bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  "roleName" varchar
);

create table if not exists public.venue_type (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  name        text not null,
  description text not null
);

create table if not exists public.instrument (
  id         bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name       text
);

-- ============================ CORE ENTITIES ==================================

-- profile — app users / "performers"; PK is the Supabase auth user id.
create table if not exists public.profile (
  id         uuid primary key references auth.users (id) on delete cascade,
  created_at timestamptz not null default now(),
  nickname   varchar,
  role       bigint default '3'::bigint references public.role (id),
  avatar_url text,
  email      text,
  constraint user_auth_id_key unique (id)   -- legacy unique, redundant with PK
);

-- venue — places where gigs ("toques") happen.
create table if not exists public.venue (
  id              bigint generated by default as identity primary key,
  created_at      timestamptz not null default now(),
  name            varchar,
  address         varchar,
  contact_name    varchar,
  contact         varchar,            -- free-form handle, e.g. "@acturo"
  venue_type      bigint references public.venue_type (id),
  allow_party     boolean not null default true,
  allow_rehearsal boolean not null default false,
  created_by      uuid references public.profile (id),
  whatsapp        text,               -- added via the venue_contact branch
  instagram       text                -- added via the venue_contact branch
);

-- venue_admin — who may administer a venue (besides its creator).
-- NOTE: created_at is timestamp WITHOUT time zone (inconsistent with the other
-- tables' timestamptz). PK + user_id NOT NULL added 2026-08-11 (advisor fix).
create table if not exists public.venue_admin (
  venue_id   bigint not null references public.venue (id),
  created_at timestamp default now(),
  user_id    uuid not null references public.profile (id),
  primary key (venue_id, user_id)
);

-- party — a gig ("toque") at a venue on a date.
-- status lifecycle (see docs/specs/party-status.md): draft -> pending_venue ->
-- confirmed -> live -> completed, plus cancelled. status is the source of truth
-- approvals / live mode / discovery read from; approved_by_venue is superseded.
create table if not exists public.party (
  id                bigint generated by default as identity primary key,
  created_at        timestamptz not null default now(),
  date              date,
  venue             bigint references public.venue (id),
  title             text,
  description       text,
  approved_by_venue boolean not null default false,
  created_by        uuid references public.profile (id),
  status            public.party_status not null default 'draft',
  status_changed_at timestamptz not null default now(),
  cancel_reason     text
);

-- party_admin — who may administer a party (besides its creator).
create table if not exists public.party_admin (
  party_id   bigint not null references public.party (id),
  created_at timestamptz not null default now(),
  user_id    uuid not null references public.profile (id),
  primary key (party_id, user_id)
);

-- song — tracks; MusicBrainz-sourced, linked to Spotify.
create table if not exists public.song (
  id         bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  title      varchar,
  artist     varchar,
  added_by   uuid references public.profile (id),
  duration   real default '3'::real,
  ref_link   text,
  constraint song_ref_link_key unique (ref_link),
  constraint unique_song_artist unique (title, artist)
);

create index if not exists idx_song_title_trgm  on public.song using gin (title  gin_trgm_ops);
create index if not exists idx_song_artist_trgm on public.song using gin (artist gin_trgm_ops);

-- performance — a song slotted into a party's set list (drag-orderable).
create table if not exists public.performance (
  id           bigint generated by default as identity primary key,
  created_at   timestamptz not null default now(),
  party        bigint references public.party (id),
  song         bigint references public.song (id),
  ref_link     varchar,
  key          varchar,             -- musical key
  "order"      smallint,            -- set-list position (reserved word — quoted)
  suggested_by uuid references public.profile (id)
);

-- performance_user — a performer (user) playing an instrument in a performance.
create table if not exists public.performance_user (
  performance_id bigint not null references public.performance (id),
  created_at     timestamptz not null default now(),
  instrument_id  bigint not null references public.instrument (id),
  user_id        uuid   not null references public.profile (id),
  primary key (performance_id, instrument_id, user_id)
);

-- ---- foreign-key covering indexes (advisor fix 2026-08-11) ------------------
-- venue_admin.venue_id is covered by its composite PK, so it's omitted here.
create index if not exists idx_party_created_by            on public.party (created_by);
create index if not exists idx_party_venue                 on public.party (venue);
create index if not exists idx_party_admin_user_id         on public.party_admin (user_id);
create index if not exists idx_performance_party           on public.performance (party);
create index if not exists idx_performance_song            on public.performance (song);
create index if not exists idx_performance_suggested_by    on public.performance (suggested_by);
create index if not exists idx_performance_user_instrument on public.performance_user (instrument_id);
create index if not exists idx_performance_user_user_id    on public.performance_user (user_id);
create index if not exists idx_profile_role                on public.profile (role);
create index if not exists idx_song_added_by               on public.song (added_by);
create index if not exists idx_venue_created_by            on public.venue (created_by);
create index if not exists idx_venue_venue_type            on public.venue (venue_type);
create index if not exists idx_venue_admin_user_id         on public.venue_admin (user_id);

-- =============================================================================
-- FUNCTIONS & TRIGGERS
-- =============================================================================
-- can_see_party: party visibility used by the performance SELECT policy.
-- SECURITY INVOKER — runs as the caller and leans on party's own SELECT policy
-- for the visibility rule (single source of truth; no public security-definer
-- RPC to worry about). No recursion: party's policy doesn't reference performance.
create or replace function public.can_see_party(pid bigint)
returns boolean language sql stable security invoker set search_path = '' as $$
  select exists (select 1 from public.party p where p.id = pid);
$$;

-- keep party.status_changed_at fresh on status transitions
create or replace function public.set_status_changed_at()
returns trigger language plpgsql set search_path = '' as $$
begin
  if new.status is distinct from old.status then
    new.status_changed_at = now();
  end if;
  return new;
end;
$$;

create trigger party_status_changed
  before update on public.party
  for each row execute function public.set_status_changed_at();

-- (public.auto_add_admin also exists: a trigger that auto-adds a party's
--  creator as a party_admin on insert.)

-- =============================================================================
-- ROW LEVEL SECURITY
-- =============================================================================
-- RLS is ENABLED on every table. General pattern:
--   * SELECT: open to anon + authenticated (public read app), EXCEPT party and
--     performance, which are gated by party status/visibility (drafts, pending,
--     and cancelled toques + their setlists are hidden from the public — see
--     the party/performance policies and can_see_party()).
--   * INSERT: any authenticated user.
--   * UPDATE/DELETE: restricted to owners/admins via *_admin tables.
--
-- SECURITY NOTES worth reviewing (Epic 2):
--   * performance UPDATE is restricted to the parent party's owner/admins, and
--     performance_user UPDATE to the owning user (tightened 2026-08-11; see
--     migrations/20260811_tighten_performance_update_rls.sql). INSERT remains
--     open to any authenticated user by design (collaborative suggestions).
--   * Core tables (party, venue, song, profile, performance) have NO DELETE
--     policy, so with RLS on, deletes are denied to anon/authenticated.
--   * The lookup tables `role`, `venue_type`, `instrument` are publicly
--     readable (SELECT to all). No table is deny-all anymore.
--   * auth.uid() is wrapped as (select auth.uid()) in the owner/admin policies
--     so it's evaluated once per query, not per row (advisor fix 2026-08-11;
--     see migrations/20260811_advisor_fixes.sql).
-- =============================================================================

alter table public.role              enable row level security;
alter table public.venue_type        enable row level security;
alter table public.instrument        enable row level security;
alter table public.profile           enable row level security;
alter table public.venue             enable row level security;
alter table public.venue_admin       enable row level security;
alter table public.party             enable row level security;
alter table public.party_admin       enable row level security;
alter table public.song              enable row level security;
alter table public.performance       enable row level security;
alter table public.performance_user  enable row level security;

-- ---- song -------------------------------------------------------------------
create policy "allow select to all users" on public.song
  for select to anon, authenticated using (true);
create policy "allow insert to authenticated users" on public.song
  for insert to authenticated with check (true);

-- ---- venue ------------------------------------------------------------------
create policy "allow select to all users" on public.venue
  for select to anon, authenticated using (true);
create policy "allow insert to authenticated users" on public.venue
  for insert to authenticated with check (true);
create policy "allow update to venue admins" on public.venue
  for update using (
    (created_by = (select auth.uid()))
    or exists (
      select 1 from public.venue_admin
      where venue_admin.venue_id = venue.id and venue_admin.user_id = (select auth.uid())
    )
  );

-- ---- venue_admin ------------------------------------------------------------
create policy "Enable read access for all users" on public.venue_admin
  for select to anon, authenticated using (true);
create policy "allow insert for party admins" on public.venue_admin
  for insert to authenticated with check (
    ((select venue.created_by from public.venue where venue.id = venue_admin.venue_id) = (select auth.uid()))
    or exists (
      select 1 from public.venue_admin venue_admin_1
      where venue_admin_1.venue_id = venue_admin.venue_id and venue_admin_1.user_id = (select auth.uid())
    )
  );
create policy "allow delete for venue admins" on public.venue_admin
  for delete to authenticated using (
    ((select auth.uid()) = user_id)
    or exists (
      select 1 from public.venue_admin venue_admin_1
      where venue_admin_1.venue_id = venue_admin.venue_id and venue_admin_1.user_id = auth.uid()
    )
  );

-- ---- party ------------------------------------------------------------------
-- Public statuses are world-readable; drafts/pending/cancelled only to the
-- owner, party admins, or the venue's admins (see docs/specs/party-status.md).
create policy "select party: public statuses or owner/admins" on public.party
  for select to anon, authenticated
  using (
    status in ('confirmed', 'live', 'completed')
    or created_by = (select auth.uid())
    or exists (select 1 from public.party_admin pa
               where pa.party_id = party.id and pa.user_id = (select auth.uid()))
    or exists (select 1 from public.venue_admin va
               where va.venue_id = party.venue and va.user_id = (select auth.uid()))
  );
create policy "allow insert to authenticated users" on public.party
  for insert to authenticated with check (true);
create policy "allow update to party admins" on public.party
  for update to authenticated using (
    (created_by = (select auth.uid()))
    or exists (
      select 1 from public.party_admin
      where party_admin.party_id = party.id and party_admin.user_id = (select auth.uid())
    )
  ) with check (true);

-- ---- party_admin ------------------------------------------------------------
create policy "Enable read access for authenticated users" on public.party_admin
  for select to authenticated using (true);
create policy "allow Insert to party owner and other party admins" on public.party_admin
  for insert to authenticated with check (
    ((select party.created_by from public.party where party.id = party_admin.party_id) = (select auth.uid()))
    or exists (
      select 1 from public.party_admin party_admin_1
      where party_admin_1.party_id = party_admin.party_id and party_admin_1.user_id = (select auth.uid())
    )
  );
create policy "Enable delete for party admins" on public.party_admin
  for delete to authenticated using (
    ((select auth.uid()) = user_id)
    or exists (
      select 1 from public.party_admin party_admin_1
      where party_admin_1.party_id = party_admin.party_id and party_admin_1.user_id = auth.uid()
    )
  );

-- ---- performance ------------------------------------------------------------
-- A hidden party's setlist stays hidden (gated by parent-party visibility).
create policy "select performance: parent party visible" on public.performance
  for select to anon, authenticated
  using (public.can_see_party(performance.party));
create policy "allow insert to authenticated users" on public.performance
  for insert to authenticated with check (true);
create policy "Enable Update for authenticated users only" on public.performance
  for update to authenticated using (
    exists (
      select 1 from public.party p
      where p.id = performance.party
        and (
          p.created_by = (select auth.uid())
          or exists (
            select 1 from public.party_admin pa
            where pa.party_id = p.id and pa.user_id = (select auth.uid())
          )
        )
    )
  );

-- ---- performance_user -------------------------------------------------------
create policy "allow select to all users" on public.performance_user
  for select to anon, authenticated using (true);
create policy "allow insert to authenticated users" on public.performance_user
  for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.performance_user
  for update to authenticated using (user_id = (select auth.uid()));
create policy "allow delete to own user" on public.performance_user
  for delete to authenticated using (user_id = (select auth.uid()));

-- ---- profile ----------------------------------------------------------------
create policy "allow select to all users" on public.profile
  for select to anon, authenticated using (true);
create policy "allow insert to authenticated users" on public.profile
  for insert to authenticated with check (true);
create policy "allow update to own user" on public.profile
  for update to authenticated using (id = (select auth.uid()));

-- ---- instrument -------------------------------------------------------------
create policy "Enable read access for all users" on public.instrument
  for select to anon, authenticated using (true);

-- ---- venue_type -------------------------------------------------------------
create policy "Enable read access for all users" on public.venue_type
  for select to public using (true);

-- ---- role -------------------------------------------------------------------
create policy "Enable read access for all users" on public.role
  for select to anon, authenticated using (true);
