-- =============================================================================
-- Migration: in-app notifications center (#57) — the keystone surface
-- Date: 2026-08-25
-- =============================================================================
-- A `notification` table other features write into, plus the first producer:
-- party status changes. Notifications are created ONLY by SECURITY DEFINER
-- triggers on real events — clients never insert (that would let anyone spam any
-- user's inbox). Recipients read / mark-read / delete only their own rows.
--
-- #51 extends the producers (live, day-before reminders, signup requests, etc.).
-- =============================================================================

begin;

create table if not exists public.notification (
  id         bigint generated by default as identity primary key,
  recipient  uuid  not null references public.profile (id) on delete cascade,
  type       text  not null,               -- e.g. party_approved, party_declined
  payload    jsonb not null default '{}'::jsonb,  -- { party_id, party_title, reason, ... }
  read_at    timestamptz,                   -- null = unread
  created_at timestamptz not null default now()
);
create index if not exists idx_notification_recipient on public.notification (recipient, created_at desc);
create index if not exists idx_notification_unread     on public.notification (recipient) where read_at is null;

alter table public.notification enable row level security;
-- Own-only read / mark-read / delete. No INSERT policy: rows come from the
-- SECURITY DEFINER trigger below (which bypasses RLS as the table owner).
create policy "notification select own" on public.notification
  for select to authenticated using (recipient = (select auth.uid()));
create policy "notification update own" on public.notification
  for update to authenticated using (recipient = (select auth.uid()));
create policy "notification delete own" on public.notification
  for delete to authenticated using (recipient = (select auth.uid()));

-- Producer: fire notifications on party status transitions. The recipient is
-- never the actor (the venue acts → the organizer is told; a toque goes pending
-- → the venue's admins are told), so these are always about someone else's move.
create or replace function public.notify_party_status()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  if new.status is distinct from old.status then
    -- Venue approved a pending toque → organizer.
    if new.status = 'confirmed' and old.status = 'pending_venue' and new.created_by is not null then
      insert into public.notification (recipient, type, payload)
      values (new.created_by, 'party_approved',
              jsonb_build_object('party_id', new.id, 'party_title', new.title));

    -- Venue declined a pending toque, or cancelled a confirmed one → organizer.
    elsif new.status = 'cancelled'
      and new.cancel_reason in ('venue_declined', 'venue_cancelled')
      and new.created_by is not null then
      insert into public.notification (recipient, type, payload)
      values (new.created_by,
              case when new.cancel_reason = 'venue_declined'
                   then 'party_declined' else 'party_venue_cancelled' end,
              jsonb_build_object('party_id', new.id, 'party_title', new.title, 'reason', new.cancel_note));

    -- Toque sent to the venue for approval → the venue's owner + admins.
    elsif new.status = 'pending_venue' then
      insert into public.notification (recipient, type, payload)
      select uid, 'party_pending_venue',
             jsonb_build_object('party_id', new.id, 'party_title', new.title)
      from (
        select v.created_by as uid from public.venue v
          where v.id = new.venue and v.created_by is not null
        union
        select va.user_id from public.venue_admin va where va.venue_id = new.venue
      ) recips;
    end if;
  end if;
  return new;
end; $$;

drop trigger if exists party_status_notify on public.party;
create trigger party_status_notify
  after update on public.party
  for each row execute function public.notify_party_status();

commit;
