-- =============================================================================
-- Migration: venue profile — equipment, fees, restrictions, approval (#30)
-- Date: 2026-08-21
-- =============================================================================
-- Makes a venue decision-useful (see docs/specs/venue-profile.md):
--   * equipment/backline — curated `equipment` lookup + `venue_equipment`
--     junction (structured, filterable), same pattern as instrument/perf_user.
--   * engagement model & fees — engagement_model enum + engagement_notes text.
--   * restrictions — min_age, curfew, capacity + house_rules freeform.
--   * hosting approval — requires_approval bool (default true), which the party
--     status flow (#31) will read for the pending_venue path.
-- All additive. Venue field edits are already covered by the venue UPDATE policy
-- (created_by OR venue_admin); venue_equipment gets matching insert/delete RLS.
-- =============================================================================

begin;

-- ---- engagement model enum --------------------------------------------------
create type public.engagement_model as enum (
  'free', 'door_split', 'guarantee', 'pay_to_play', 'tips', 'bar_minimum', 'other'
);

-- ---- venue field additions --------------------------------------------------
alter table public.venue
  add column if not exists requires_approval boolean not null default true,
  add column if not exists engagement_model  public.engagement_model,
  add column if not exists engagement_notes  text,
  add column if not exists min_age           smallint,
  add column if not exists curfew            time,
  add column if not exists capacity          integer,
  add column if not exists house_rules       text;

-- ---- equipment lookup + venue_equipment junction ----------------------------
create table if not exists public.equipment (
  id         bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name       text not null,
  category   text
);

create table if not exists public.venue_equipment (
  venue_id     bigint not null references public.venue (id) on delete cascade,
  equipment_id bigint not null references public.equipment (id),
  quantity     integer,   -- e.g. 4 microphones; null = unspecified
  notes        text,      -- description: brand / model / size specifics
  created_at   timestamptz not null default now(),
  primary key (venue_id, equipment_id)
);
create index if not exists idx_venue_equipment_equipment
  on public.venue_equipment (equipment_id);

-- ---- seed the curated equipment list ----------------------------------------
insert into public.equipment (name, category) values
  ('Sistema de sonido (PA)',   'sonido'),
  ('Consola de mezcla',        'sonido'),
  ('Micrófonos',               'sonido'),
  ('Monitores',                'sonido'),
  ('Cajas DI',                 'sonido'),
  ('Batería',                  'backline'),
  ('Amplificador de guitarra', 'backline'),
  ('Amplificador de bajo',     'backline'),
  ('Teclado/Piano',            'backline'),
  ('Tarima',                   'escenario'),
  ('Iluminación',              'escenario')
on conflict do nothing;

-- ---- RLS: equipment (public lookup) -----------------------------------------
alter table public.equipment enable row level security;
create policy "allow select to all users" on public.equipment
  for select to anon, authenticated using (true);

-- ---- RLS: venue_equipment ---------------------------------------------------
-- Readable by all; managed by the venue's creator or its admins (mirrors the
-- venue UPDATE / venue_admin ownership check).
alter table public.venue_equipment enable row level security;

create policy "allow select to all users" on public.venue_equipment
  for select to anon, authenticated using (true);

create policy "venue admins insert equipment" on public.venue_equipment
  for insert to authenticated with check (
    ((select venue.created_by from public.venue where venue.id = venue_equipment.venue_id) = (select auth.uid()))
    or exists (
      select 1 from public.venue_admin
      where venue_admin.venue_id = venue_equipment.venue_id
        and venue_admin.user_id = (select auth.uid())
    )
  );

create policy "venue admins delete equipment" on public.venue_equipment
  for delete to authenticated using (
    ((select venue.created_by from public.venue where venue.id = venue_equipment.venue_id) = (select auth.uid()))
    or exists (
      select 1 from public.venue_admin
      where venue_admin.venue_id = venue_equipment.venue_id
        and venue_admin.user_id = (select auth.uid())
    )
  );

commit;
