-- =============================================================================
-- Migration: party_set — a band's block as one orderable thing (#110), STAGE 1
-- Date: 2026-09-11
-- =============================================================================
-- ADDITIVE. Safe to apply BEFORE the matching deploy, and it is meant to go
-- first — the trigger below is what lets the CURRENT client keep inserting
-- performances with no knowledge of sets.
--
-- Deliberately NOT in this migration, because both would break the live client
-- the moment they were applied (see 20260911_drop_profile_role.sql for the last
-- time that ordering mattered):
--   * `performance.set_id` staying NULLABLE. The trigger fills it in, so every
--     row has one in practice, but a NOT NULL would turn any gap into a failed
--     insert instead of a fixable row.
--   * Tightening the `performance` INSERT policy. Today it is `with check
--     (true)`; narrowing it to "open set, or a member of the set's band, or a
--     party admin" is stage 2, after the client knows how to pass a set.
--
-- -----------------------------------------------------------------------------
-- The one thing to understand about this migration
-- -----------------------------------------------------------------------------
-- `performance."order"` changes MEANING — from "position in the night" to
-- "position in my set". The backfill therefore does NOT renumber it.
--
-- That is the whole trick that makes this safe to apply early. Sets are derived
-- from runs that are ALREADY contiguous in the existing order, so within a set
-- the old values are already ascending, and sets themselves are numbered in the
-- order their songs already appear. Both readings agree:
--
--   old client:  order by pf."order"                    -> unchanged running order
--   new client:  order by s."order", pf."order"         -> identical, today
--
-- They only diverge once somebody moves a set, which needs UI that does not
-- exist yet. Renumbering to 1..n per set would have broken the old client the
-- instant this ran.
-- =============================================================================

begin;

-- -----------------------------------------------------------------------------
-- party_set
-- -----------------------------------------------------------------------------
-- A set is a CONTAINER of performances, not a replacement for one. A
-- performance carries four things that are irreducibly per-song — live_state
-- (which IS the now-playing pointer, #37), applause targets, performance_user,
-- and started_at/ended_at — so collapsing a band's block into a single
-- performance row would destroy all four. A night is a sequence of sets; a set
-- is a sequence of songs.
--
-- band_id NULL means an OPEN set: anyone may add to it, and it is created and
-- garbage-collected implicitly (see the triggers below). Nobody names or manages
-- one, which is what keeps a pure jam night — most nights — looking exactly as
-- it does today.
--
-- No unique constraint on (party_id, band_id) ON PURPOSE: a headliner playing
-- two sets with an open block between them is a normal shape for this kind of
-- night, and it is how Monster Mash's already-split block derives losslessly
-- below instead of having its running order rewritten.
create table if not exists public.party_set (
  id         bigint generated by default as identity primary key,
  party_id   bigint not null references public.party (id) on delete cascade,
  band_id    bigint references public.band (id) on delete cascade,
  "order"    smallint not null,     -- position in the night (reserved word — quoted)
  title      text,                  -- optional: "Jam abierto", "Pulse · 2º set"
  created_at timestamptz not null default now()
);

create index if not exists idx_party_set_party on public.party_set (party_id, "order");
create index if not exists idx_party_set_band on public.party_set (band_id);

alter table public.performance
  add column if not exists set_id bigint references public.party_set (id) on delete cascade;

-- The setlist read is "every performance of this party, by set then position",
-- so the useful index is the one that serves that join.
create index if not exists idx_performance_set on public.performance (set_id, "order");

-- -----------------------------------------------------------------------------
-- RLS
-- -----------------------------------------------------------------------------
alter table public.party_set enable row level security;

-- Visible exactly when its party is. can_see_party() already folds in the
-- is_test / status rules, so the flyer and the public setlist inherit them.
drop policy if exists "select party_set: parent party visible" on public.party_set;
create policy "select party_set: parent party visible" on public.party_set
  for select to anon, authenticated
  using (public.can_see_party(party_set.party_id));

-- Writes are party-admin only. A BAND reorders its own songs, which is
-- `performance."order"` and goes through reorder_set_songs() below — it never
-- needs to write party_set itself. Creating an open set is done by the trigger,
-- which is SECURITY DEFINER and bypasses this.
drop policy if exists "party_set: admins manage" on public.party_set;
create policy "party_set: admins manage" on public.party_set
  for all to authenticated
  using (public.is_party_admin(party_set.party_id))
  with check (public.is_party_admin(party_set.party_id));

-- -----------------------------------------------------------------------------
-- Backfill: derive sets from the contiguous runs already in the data
-- -----------------------------------------------------------------------------
-- Classic gaps-and-islands: the difference between "position in the party" and
-- "position among this band's songs" is constant within a run and changes at
-- every boundary, so it identifies the islands.
--
-- Measured before writing this (all six parties with performances):
--   party  5 Serenata Rock        9 perfs -> 1 set  (open)
--   party  9 Happy Birthday Cami 23 perfs -> 1 set  (open)
--   party 10 Amistad y Amor      10 perfs -> 1 set  (band)
--   party 11 Monster Mash [test] 21 perfs -> 3 sets (INTERLEAVED — the case
--            that motivated the ticket; derives losslessly into open/band/open
--            rather than being merged, so a past running order is not rewritten)
--   party 25 Halloween Fest      15 perfs -> 2 sets (band, then open)
--   party 37 Jojoprueba [LIVE]    4 perfs -> 1 set  (open)
--
-- Party 37 is mid-show. Nothing here writes "order", live_state, started_at or
-- ended_at, so a running show is untouched.
with islands as (
  select
    pf.party,
    pf.id,
    pf.band_id,
    pf."order",
    row_number() over (partition by pf.party order by pf."order" nulls last, pf.id)
      - row_number() over (partition by pf.party, pf.band_id order by pf."order" nulls last, pf.id)
      as grp
  from public.performance pf
  where pf.set_id is null
),
blocks as (
  select party, band_id, grp,
         min("order") as first_order,
         min(id)      as first_id
  from islands
  group by party, band_id, grp
),
numbered as (
  select party, band_id, grp,
         (row_number() over (partition by party order by first_order nulls last, first_id))::smallint as set_order
  from blocks
),
created as (
  insert into public.party_set (party_id, band_id, "order")
  select party, band_id, set_order from numbered
  returning id, party_id, band_id, "order"
)
update public.performance pf
set set_id = c.id
from islands i
join numbered n on n.party = i.party and n.grp = i.grp and n.band_id is not distinct from i.band_id
join created c on c.party_id = i.party
             and c.band_id is not distinct from i.band_id
             and c."order" = n.set_order
where pf.id = i.id;

-- -----------------------------------------------------------------------------
-- Implicit open sets: the trigger that makes stage-1 safe
-- -----------------------------------------------------------------------------
-- Every performance belongs to a set, but nobody should have to know that. This
-- assigns one when the caller does not name it, which is what keeps the CURRENT
-- client — which has never heard of party_set — inserting successfully.
--
-- The rule matches what the UI will do explicitly later: a loose song joins the
-- trailing OPEN set if there is one, and otherwise starts a new open set after
-- the last block. So "add a song" lands at the end of the night, as it does now.
--
-- SECURITY DEFINER: creating the party_set row must not depend on the inserter
-- being a party admin — an ordinary musician adding a song to a jam is the
-- common case.
--
-- Known wart, left unfixed on purpose: two people adding the first loose song at
-- the same instant can each create a trailing open set. The result is two
-- adjacent open blocks, which reads fine, reorders fine and merges the moment
-- one is emptied by the GC below. Serialising it would mean locking the party on
-- every insert, which is a real cost against a cosmetic and self-healing race.
create or replace function public.assign_performance_set()
returns trigger language plpgsql security definer set search_path = '' as $$
declare
  v_set bigint;
begin
  if new.set_id is not null or new.party is null then
    return new;
  end if;

  select id into v_set
  from public.party_set
  where party_id = new.party and band_id is null
  order by "order" desc
  limit 1;

  if v_set is null then
    insert into public.party_set (party_id, band_id, "order")
    select new.party, null,
           (coalesce(max("order"), 0) + 1)::smallint
    from public.party_set where party_id = new.party
    returning id into v_set;
  end if;

  new.set_id := v_set;
  return new;
end;
$$;

drop trigger if exists trg_assign_performance_set on public.performance;
create trigger trg_assign_performance_set
  before insert on public.performance
  for each row execute function public.assign_performance_set();

-- Garbage-collect an open set once its last song leaves. Only OPEN sets: a band
-- set is a deliberate thing an organizer placed in the running order, and an
-- empty one is "Pulse is playing, we just haven't picked the songs yet".
create or replace function public.gc_empty_open_set()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  if old.set_id is null then
    return null;
  end if;
  delete from public.party_set s
  where s.id = old.set_id
    and s.band_id is null
    and not exists (select 1 from public.performance p where p.set_id = s.id);
  return null;
end;
$$;

drop trigger if exists trg_gc_empty_open_set on public.performance;
create trigger trg_gc_empty_open_set
  after delete on public.performance
  for each row execute function public.gc_empty_open_set();

-- -----------------------------------------------------------------------------
-- Who may rearrange a set's songs
-- -----------------------------------------------------------------------------
-- can_sign_up_band(), NOT is_band_manager(). That is not a new decision: it is
-- the function sign_band_up() already uses, and it reads `band.who_can_sign_up`
-- — a setting the band itself chose. A manager-only rule would contradict that
-- setting, and would make REARRANGING YOUR OWN SONGS stricter than COMMITTING
-- THE BAND TO A GIG, which is backwards.
create or replace function public.can_edit_set(sid bigint)
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.party_set s
    where s.id = sid
      and (
        public.is_party_admin(s.party_id)
        or (s.band_id is not null and public.can_sign_up_band(s.band_id))
      )
  );
$$;

-- -----------------------------------------------------------------------------
-- Reordering: RPCs, because RLS cannot restrict WHICH COLUMNS an update touches
-- -----------------------------------------------------------------------------
-- Letting a band reorder its own songs by widening the `performance` UPDATE
-- policy would hand band members `song`, `party`, `live_state`, `key` and
-- `band_id` on those rows as well. Same limitation that forced #95's
-- confirm_requirement, #100's set_song_reviewed and the whole of #99 into
-- SECURITY DEFINER RPCs. Both of these write ONLY "order".
--
-- Both also validate that every id passed in belongs to the party/set in
-- question. Without that the array argument is a way to reorder someone else's
-- night: pass their ids, get their running order rewritten.
--
-- Side benefit: reordering today is one UPDATE round trip PER ROW PER MOVE —
-- moving one song in a fifteen-song list is fifteen requests. These take the
-- whole ordered array in one call (same class of fix as #84).

create or replace function public.reorder_sets(p_party bigint, p_set_ids bigint[])
returns void language plpgsql security definer set search_path = '' as $$
declare
  v_count int;
begin
  if not public.is_party_admin(p_party) then
    raise exception 'only a party admin can reorder the running order';
  end if;

  -- Every id must belong to THIS party, and the array must name all of them —
  -- a partial array would leave the unnamed sets holding stale positions.
  select count(*) into v_count from public.party_set where party_id = p_party;
  if v_count <> coalesce(array_length(p_set_ids, 1), 0) then
    raise exception 'expected % set ids for this toque, got %',
      v_count, coalesce(array_length(p_set_ids, 1), 0);
  end if;

  if exists (
    select 1 from unnest(p_set_ids) as t(id)
    where not exists (
      select 1 from public.party_set s where s.id = t.id and s.party_id = p_party
    )
  ) then
    raise exception 'one of those sets does not belong to this toque';
  end if;

  -- WITH ORDINALITY, not row_number() over () — only the former is guaranteed
  -- to reflect the array's own order. Getting this wrong would scramble the
  -- running order rather than set it.
  update public.party_set s
  set "order" = t.ord::smallint
  from unnest(p_set_ids) with ordinality as t(id, ord)
  where s.id = t.id;
end;
$$;

create or replace function public.reorder_set_songs(p_set bigint, p_performance_ids bigint[])
returns void language plpgsql security definer set search_path = '' as $$
declare
  v_count int;
begin
  if not public.can_edit_set(p_set) then
    raise exception 'you cannot rearrange this set';
  end if;

  select count(*) into v_count from public.performance where set_id = p_set;
  if v_count <> coalesce(array_length(p_performance_ids, 1), 0) then
    raise exception 'expected % songs for this set, got %',
      v_count, coalesce(array_length(p_performance_ids, 1), 0);
  end if;

  if exists (
    select 1 from unnest(p_performance_ids) as t(id)
    where not exists (
      select 1 from public.performance p where p.id = t.id and p.set_id = p_set
    )
  ) then
    raise exception 'one of those songs is not in this set';
  end if;

  update public.performance p
  set "order" = t.ord::smallint
  from unnest(p_performance_ids) with ordinality as t(id, ord)
  where p.id = t.id;
end;
$$;

-- -----------------------------------------------------------------------------
-- Live mode learns the second level
-- -----------------------------------------------------------------------------
-- The running order is what a room full of people is looking at, so this is the
-- riskiest part of the change. Three functions pick "the next queued song" and
-- all three use the identical `order by "order" nulls last, id limit 1`; each
-- becomes a join to party_set ordered by set first.
--
-- NOTE: the spec listed FOUR functions. undo_last_move is not one of them — it
-- orders by `ended_at desc`, i.e. by what actually happened, not by the running
-- order, so it is correct as it stands. jump_to_song and end_current_song do not
-- order at all.
--
-- `nulls last` on BOTH levels: set_id is nullable during this stage, so a row
-- inserted by a client that predates the trigger sorts to the end of the night —
-- which is where "add a song" puts it anyway.

create or replace function public.start_show(p_party bigint)
returns bigint
language plpgsql
set search_path = ''
as $$
declare
  v_first bigint;
begin
  if not public.is_party_admin(p_party) then
    raise exception 'only a party admin can start the show';
  end if;

  update public.party set status = 'live'
  where id = p_party and status in ('confirmed', 'live');
  if not found then
    raise exception 'this toque cannot be started (must be confirmed)';
  end if;

  -- Already running? Leave the current song alone.
  select id into v_first from public.performance
  where party = p_party and live_state = 'playing' limit 1;
  if v_first is not null then
    return v_first;
  end if;

  select pf.id into v_first
  from public.performance pf
  left join public.party_set s on s.id = pf.set_id
  where pf.party = p_party and pf.live_state = 'queued'
  order by s."order" nulls last, pf."order" nulls last, pf.id
  limit 1;

  if v_first is not null then
    update public.performance
    set live_state = 'playing', started_at = now(), ended_at = null
    where id = v_first;
  end if;

  return v_first;
end;
$$;

create or replace function public.advance_show(p_party bigint)
returns bigint
language plpgsql
set search_path = ''
as $$
declare
  v_next bigint;
begin
  if not public.is_party_admin(p_party) then
    raise exception 'only a party admin can run the show';
  end if;

  -- Close the current song first, so the partial unique index is free.
  update public.performance
  set live_state = 'played', ended_at = now()
  where party = p_party and live_state = 'playing';

  select pf.id into v_next
  from public.performance pf
  left join public.party_set s on s.id = pf.set_id
  where pf.party = p_party and pf.live_state = 'queued'
  order by s."order" nulls last, pf."order" nulls last, pf.id
  limit 1;

  if v_next is not null then
    update public.performance
    set live_state = 'playing', started_at = now(), ended_at = null
    where id = v_next;
  end if;

  return v_next;
end;
$$;

create or replace function public.skip_song(p_party bigint)
returns bigint
language plpgsql
set search_path = ''
as $$
declare
  v_next bigint;
begin
  if not public.is_party_admin(p_party) then
    raise exception 'only a party admin can run the show';
  end if;

  update public.performance
  set live_state = 'skipped', ended_at = now()
  where party = p_party and live_state = 'playing';

  select pf.id into v_next
  from public.performance pf
  left join public.party_set s on s.id = pf.set_id
  where pf.party = p_party and pf.live_state = 'queued'
  order by s."order" nulls last, pf."order" nulls last, pf.id
  limit 1;

  if v_next is not null then
    update public.performance
    set live_state = 'playing', started_at = now(), ended_at = null
    where id = v_next;
  end if;

  return v_next;
end;
$$;

-- -----------------------------------------------------------------------------
-- Grants
-- -----------------------------------------------------------------------------
-- `create function` grants EXECUTE to PUBLIC, and Supabase's pg_default_acl
-- grants it to anon/authenticated BY NAME — so revoking from anon/authenticated
-- alone is a no-op. Revoke all three, then grant back deliberately.
revoke all on function public.reorder_sets(bigint, bigint[]) from public, anon, authenticated;
revoke all on function public.reorder_set_songs(bigint, bigint[]) from public, anon, authenticated;
grant execute on function public.reorder_sets(bigint, bigint[]) to authenticated;
grant execute on function public.reorder_set_songs(bigint, bigint[]) to authenticated;

-- can_edit_set is a read used by the client to decide whether to render the
-- controls. anon never can, but it must be EXECUTABLE by anon rather than
-- error — a definer function a caller cannot execute raises permission-denied
-- instead of returning false (the #102 lesson).
revoke all on function public.can_edit_set(bigint) from public;
grant execute on function public.can_edit_set(bigint) to anon, authenticated;

-- The triggers' functions are called by the trigger, never directly.
revoke all on function public.assign_performance_set() from public, anon, authenticated;
revoke all on function public.gc_empty_open_set() from public, anon, authenticated;

commit;

-- =============================================================================
-- After applying: reconcile supabase/schema.sql and regenerate
-- src/lib/database.types.ts (new table + new column + four new functions).
--
-- STAGE 2, only AFTER the client deploy that understands sets:
--   * alter table public.performance alter column set_id set not null;
--   * replace the `performance` INSERT policy (`with check (true)` today) with:
--       the target set is open, OR the inserter can_sign_up_band(set.band_id),
--       OR they are a party admin.
--     Worth doing on its own merits — today anyone signed in can insert a
--     performance into any party.
--   * refuse removing a set while the party is `live` and it holds the
--     now-playing pointer, which would otherwise strand advance_show().
-- =============================================================================
