-- =============================================================================
-- Migration: event logistics — requirements, roles (#95, Stage 1)
-- Date: 2026-09-08
-- =============================================================================
-- Spec: docs/specs/event-logistics.md
--
-- The app knows what a venue HAS (venue_equipment, #30) and who is PLAYING
-- (performance_user). It knows nothing about the gap between them, which is
-- where a toque actually falls over: nobody brought a bass amp.
--
-- One table for equipment AND roles. They name different things but share the
-- whole lifecycle — needed -> sourced -> confirmed -> present on the day -> part
-- of the record — and the same UI, gap counter and checklist row. A `kind`
-- discriminator beats two tables that would duplicate all of it.
--
-- This migration lays down the FULL model from the spec, including the columns
-- Stage 2 (assignment, confirmation) and Stage 3 (the day-of tick) will use, so
-- those stages are UI work rather than another migration. Stage 1 only reads and
-- writes: kind, equipment_id/role_id, quantity, source, notes.
-- =============================================================================

begin;

-- ---------------------------------------------------------------------------
-- 1. Roles are their own lookup, not instruments
-- ---------------------------------------------------------------------------
-- An instrument is played in a PERFORMANCE — performance_user is keyed per song.
-- A sound engineer is engaged for the whole toque and plays nothing, so reusing
-- `instrument` would put a non-playing role in every song's signup list.
--
-- A table rather than an enum so adding "Fotógrafo" later is an insert, not a
-- migration with the ALTER TYPE ... ADD VALUE transaction restriction.
create table if not exists public.party_role (
  id         bigint generated by default as identity primary key,
  name       text not null,
  created_at timestamptz not null default now()
);

insert into public.party_role (name)
select v.name from (values ('Ingeniero de sonido'), ('Presentador (MC)')) as v(name)
where not exists (select 1 from public.party_role r where r.name = v.name);

-- ---------------------------------------------------------------------------
-- 2. Requirements
-- ---------------------------------------------------------------------------
do $$ begin
  create type public.requirement_kind as enum ('equipment', 'role');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.requirement_source as enum ('unassigned', 'venue', 'organizer', 'performer', 'external');
exception when duplicate_object then null; end $$;

create table if not exists public.party_requirement (
  id             bigint generated by default as identity primary key,
  party_id       bigint not null references public.party (id) on delete cascade,
  kind           public.requirement_kind not null,
  -- exactly one of these, per the checks below
  equipment_id   bigint references public.equipment (id),
  role_id        bigint references public.party_role (id),
  quantity       integer,                                   -- equipment only
  source         public.requirement_source not null default 'unassigned',

  -- WHO (Stage 2). assigned_user when they have an account; assigned_label is a
  -- display-name snapshot, kept even for app users so the record survives an
  -- account deletion and the checklist renders with no join per row.
  assigned_user  uuid references public.profile (id) on delete set null,
  assigned_label text,

  notes          text,
  confirmed_at   timestamptz,                               -- the source said yes
  checked_at     timestamptz,                               -- ticked off on the day (Stage 3)
  created_at     timestamptz not null default now(),

  constraint requirement_names_one_thing check (
    (kind = 'equipment') = (equipment_id is not null) and
    (kind = 'role')      = (role_id is not null)
  ),
  -- "two mics" makes sense; "two MCs" is two rows with two names
  constraint quantity_is_equipment_only check (kind = 'equipment' or quantity is null),
  constraint quantity_positive check (quantity is null or quantity > 0)
);

-- Deliberately NOT unique on (party_id, equipment_id): two amps from two
-- different sources are two rows, and `quantity` covers multiples from ONE
-- source. A unique index over the nullable equipment_id/role_id pair would not
-- dedupe anyway — Postgres treats NULLs as distinct (see the applause migrations
-- for where that bit us before).
create index if not exists idx_party_requirement_party on public.party_requirement (party_id);
create index if not exists idx_party_requirement_assigned
  on public.party_requirement (assigned_user) where assigned_user is not null;
-- for Stage 4's "who brought this last time?" lookups
create index if not exists idx_party_requirement_equipment
  on public.party_requirement (equipment_id) where equipment_id is not null;
create index if not exists idx_party_requirement_role
  on public.party_requirement (role_id) where role_id is not null;

-- ---------------------------------------------------------------------------
-- 3. RLS
-- ---------------------------------------------------------------------------
alter table public.party_role        enable row level security;
alter table public.party_requirement enable row level security;

-- The role catalogue is a lookup, like instrument/equipment/venue_type.
drop policy if exists "party_role public read" on public.party_role;
create policy "party_role public read" on public.party_role
  for select to anon, authenticated using (true);

-- Requirements are visible to anyone who can see the toque. Reusing
-- can_see_party() means test-data visibility (#67) is inherited for free rather
-- than re-implemented here.
drop policy if exists "party_requirement select visible" on public.party_requirement;
create policy "party_requirement select visible" on public.party_requirement
  for select to anon, authenticated using (public.can_see_party(party_id));

-- Writes are party admins only. is_party_admin() is creator OR a party_admin
-- row, which mirrors the party UPDATE policy exactly.
drop policy if exists "party_requirement admin insert" on public.party_requirement;
create policy "party_requirement admin insert" on public.party_requirement
  for insert to authenticated with check (public.is_party_admin(party_id));

drop policy if exists "party_requirement admin update" on public.party_requirement;
create policy "party_requirement admin update" on public.party_requirement
  for update to authenticated using (public.is_party_admin(party_id));

drop policy if exists "party_requirement admin delete" on public.party_requirement;
create policy "party_requirement admin delete" on public.party_requirement
  for delete to authenticated using (public.is_party_admin(party_id));

commit;

-- =============================================================================
-- Not in this migration, on purpose
-- =============================================================================
-- * confirm_requirement() — Stage 2. When it lands it must be an RPC, not a
--   widened UPDATE policy: scoping UPDATE to `assigned_user = auth.uid()` would
--   let an assignee rewrite quantity/notes or reassign the row, and RLS cannot
--   restrict WHICH COLUMNS an update touches. And on that function,
--   `revoke ... from public, anon, authenticated` — revoking from public alone
--   leaves the named grants Supabase's default privileges add (see
--   20260908_function_grants_tighten.sql).
-- * Seeding from venue_equipment is done from the client, not a trigger: an
--   explicit organizer action can never silently clobber their edits, and
--   venue_equipment is already world-readable so no elevated privilege is needed.
-- =============================================================================
