-- =============================================================================
-- Migration: bands — data model + RLS foundation (#70, epic #40)
-- Date: 2026-09-02
-- =============================================================================
-- Persistent band entity. Musicians can be in many bands; a band has managers
-- and members, and each member's instruments are defined PER BAND (multiple
-- allowed). Bands sign up per-song inside the jam model — model (a): a band
-- OWNS the songs it plays (performance.band_id). See docs/specs/bands.md.
-- RLS is the whole security boundary (client-only app).
-- =============================================================================

begin;

-- 1. Enum ---------------------------------------------------------------------
do $$ begin
  create type public.band_role as enum ('manager', 'member');
exception when duplicate_object then null; end $$;

-- 2. Tables -------------------------------------------------------------------
create table if not exists public.band (
  id              bigint generated by default as identity primary key,
  created_at      timestamptz not null default now(),
  name            text not null,
  bio             text,
  avatar_url      text,                                   -- Storage upload (#75)
  who_can_sign_up text not null default 'members'
                  check (who_can_sign_up in ('members', 'managers')),
  created_by      uuid references public.profile (id)
);

-- membership + role (many-to-many; a musician is in many bands)
create table if not exists public.band_member (
  band_id    bigint not null references public.band (id) on delete cascade,
  user_id    uuid   not null references public.profile (id) on delete cascade,
  role       public.band_role not null default 'member',
  created_at timestamptz not null default now(),
  primary key (band_id, user_id)
);

-- what a member plays IN THIS band (multiple; independent of profile_instrument)
create table if not exists public.band_member_instrument (
  band_id       bigint not null,
  user_id       uuid   not null,
  instrument_id bigint not null references public.instrument (id),
  created_at    timestamptz not null default now(),
  primary key (band_id, user_id, instrument_id),
  foreign key (band_id, user_id)
    references public.band_member (band_id, user_id) on delete cascade
);

-- 3. Setlist links ------------------------------------------------------------
-- performance.band_id set  => the song is owned/played by that band (model a).
-- performance_user.band_id => tags the lineup rows a band signup created.
alter table public.performance      add column if not exists band_id bigint references public.band (id);
alter table public.performance_user add column if not exists band_id bigint references public.band (id);

-- FK covering indexes
create index if not exists idx_band_created_by            on public.band (created_by);
create index if not exists idx_band_member_user           on public.band_member (user_id);
create index if not exists idx_bmi_instrument             on public.band_member_instrument (instrument_id);
create index if not exists idx_performance_band           on public.performance (band_id);
create index if not exists idx_performance_user_band      on public.performance_user (band_id);

-- 4. Helpers (SECURITY DEFINER so they read band_member without RLS recursion) -
create or replace function public.is_band_manager(bid bigint)
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.band_member bm
    where bm.band_id = bid and bm.user_id = (select auth.uid()) and bm.role = 'manager'
  );
$$;

-- true when the caller may sign this band up (a member, or a manager when the
-- band restricts signup to managers).
create or replace function public.can_sign_up_band(bid bigint)
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (
    select 1
    from public.band b
    join public.band_member bm on bm.band_id = b.id
    where b.id = bid
      and bm.user_id = (select auth.uid())
      and (b.who_can_sign_up = 'members' or bm.role = 'manager')
  );
$$;

-- 5. Creator becomes the first manager (mirrors party.auto_add_admin) ----------
create or replace function public.add_band_creator_as_manager()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  if new.created_by is not null then
    insert into public.band_member (band_id, user_id, role)
    values (new.id, new.created_by, 'manager')
    on conflict (band_id, user_id) do nothing;
  end if;
  return new;
end;
$$;
drop trigger if exists band_add_creator_manager on public.band;
create trigger band_add_creator_manager
  after insert on public.band
  for each row execute function public.add_band_creator_as_manager();

-- 6. RLS ----------------------------------------------------------------------
alter table public.band                   enable row level security;
alter table public.band_member            enable row level security;
alter table public.band_member_instrument enable row level security;

-- band: public read (discoverable); creator inserts; managers edit/delete.
drop policy if exists "band select all"        on public.band;
drop policy if exists "band insert self"       on public.band;
drop policy if exists "band update managers"   on public.band;
drop policy if exists "band delete managers"   on public.band;
create policy "band select all"      on public.band for select to anon, authenticated using (true);
create policy "band insert self"     on public.band for insert to authenticated with check (created_by = (select auth.uid()));
create policy "band update managers" on public.band for update to authenticated using (public.is_band_manager(id));
create policy "band delete managers" on public.band for delete to authenticated using (public.is_band_manager(id));

-- band_member: public read (roster); managers manage; a member may leave (self).
-- The creator's manager row is added by the trigger (SECURITY DEFINER), so the
-- insert policy only needs to cover managers adding OTHER members.
drop policy if exists "band_member select all"            on public.band_member;
drop policy if exists "band_member insert managers"       on public.band_member;
drop policy if exists "band_member update managers"       on public.band_member;
drop policy if exists "band_member delete managers/self"  on public.band_member;
create policy "band_member select all"           on public.band_member for select to anon, authenticated using (true);
create policy "band_member insert managers"      on public.band_member for insert to authenticated with check (public.is_band_manager(band_id));
create policy "band_member update managers"      on public.band_member for update to authenticated using (public.is_band_manager(band_id));
create policy "band_member delete managers/self" on public.band_member for delete to authenticated using (public.is_band_manager(band_id) or user_id = (select auth.uid()));

-- band_member_instrument: public read; managers manage.
drop policy if exists "bmi select all"      on public.band_member_instrument;
drop policy if exists "bmi insert managers" on public.band_member_instrument;
drop policy if exists "bmi update managers" on public.band_member_instrument;
drop policy if exists "bmi delete managers" on public.band_member_instrument;
create policy "bmi select all"      on public.band_member_instrument for select to anon, authenticated using (true);
create policy "bmi insert managers" on public.band_member_instrument for insert to authenticated with check (public.is_band_manager(band_id));
create policy "bmi update managers" on public.band_member_instrument for update to authenticated using (public.is_band_manager(band_id));
create policy "bmi delete managers" on public.band_member_instrument for delete to authenticated using (public.is_band_manager(band_id));

-- 7. RPC: sign a band up to a song -------------------------------------------
-- SECURITY DEFINER because it inserts performance_user rows for OTHER members,
-- which the "insert self" signup policy forbids. Authorizes via can_sign_up_band,
-- claims the song for the band, then snapshots the lineup. Row status is set by
-- the existing performance_user_set_status trigger per the toque's approval mode.
create or replace function public.sign_band_up(p_performance bigint, p_band bigint)
returns void language plpgsql security definer set search_path = '' as $$
begin
  if not public.can_sign_up_band(p_band) then
    raise exception 'not allowed to sign up this band';
  end if;

  update public.performance
    set band_id = p_band
    where id = p_performance and (band_id is null or band_id = p_band);
  if not found then
    raise exception 'song not available for this band';
  end if;

  insert into public.performance_user (performance_id, user_id, instrument_id, band_id)
  select p_performance, bmi.user_id, bmi.instrument_id, p_band
  from public.band_member_instrument bmi
  where bmi.band_id = p_band
  on conflict (performance_id, instrument_id, user_id) do nothing;
end;
$$;

commit;
