-- =============================================================================
-- Migration: applause — Stage A (#38)
-- Date: 2026-09-06
-- =============================================================================
-- One clap per person per target, kept as history. See docs/specs/applause.md.
--
-- All four targets ship in the enum now even though Stage A only surfaces two:
-- ALTER TYPE ... ADD VALUE cannot have the new value USED in the same
-- transaction that adds it, so adding 'song_performer' later would mean
-- splitting a migration around that. Free here, awkward later.
-- =============================================================================

begin;

do $$
begin
  if not exists (select 1 from pg_type t join pg_namespace n on n.oid = t.typnamespace
                 where n.nspname = 'public' and t.typname = 'applause_target') then
    create type public.applause_target as enum ('event', 'performer', 'song', 'song_performer');
  end if;
end
$$;

create table if not exists public.applause (
  id             bigint generated by default as identity primary key,
  created_at     timestamptz not null default now(),
  party_id       bigint not null references public.party (id) on delete cascade,
  from_user      uuid   not null references public.profile (id) on delete cascade,
  target_type    public.applause_target not null,
  performer_id   uuid   references public.profile (id) on delete cascade,
  performance_id bigint references public.performance (id) on delete cascade,
  -- the target columns set must match target_type
  constraint applause_target_shape check (
    (target_type = 'event'          and performer_id is null     and performance_id is null) or
    (target_type = 'performer'      and performer_id is not null and performance_id is null) or
    (target_type = 'song'           and performer_id is null     and performance_id is not null) or
    (target_type = 'song_performer' and performer_id is not null and performance_id is not null)
  )
);

comment on table public.applause is
  'One deduped endorsement per person per target (#38). Not a counter — see the partial unique indexes.';

-- Dedupe. A plain unique over the nullable target columns would NOT work: in
-- Postgres NULLs are distinct in a unique index, so (me, ''event'', null, null)
-- could be inserted repeatedly. One partial index per target type instead.
create unique index if not exists applause_one_event_per_user
  on public.applause (from_user, party_id) where target_type = 'event';
create unique index if not exists applause_one_performer_per_user
  on public.applause (from_user, party_id, performer_id) where target_type = 'performer';
create unique index if not exists applause_one_song_per_user
  on public.applause (from_user, performance_id) where target_type = 'song';
-- performance_id already pins the toque, so no party_id in this one.
create unique index if not exists applause_one_song_performer_per_user
  on public.applause (from_user, performance_id, performer_id) where target_type = 'song_performer';

-- Tally lookups.
create index if not exists idx_applause_party_target on public.applause (party_id, target_type);
create index if not exists idx_applause_performance  on public.applause (performance_id);
create index if not exists idx_applause_performer    on public.applause (performer_id);

-- ---- the window + who was there --------------------------------------------
-- SECURITY DEFINER so it can read party_rsvp / performance_user without those
-- tables' policies re-entering here.
--
-- The window deliberately does NOT hang off "End show" being tapped — an
-- organizer who forgets at 2am would otherwise leave applause open forever.
-- party.date always exists.
create or replace function public.can_applaud(p_party bigint)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.party p
    where p.id = p_party
      and p.status in ('live', 'completed')
      and now() < (p.date + interval '2 days')
      and (
        -- said they were coming
        exists (select 1 from public.party_rsvp r
                where r.party_id = p.id and r.user_id = (select auth.uid()))
        -- or played it
        or exists (select 1 from public.performance perf
                   join public.performance_user pu on pu.performance_id = perf.id
                   where perf.party = p.id
                     and pu.user_id = (select auth.uid())
                     and pu.status = 'approved')
        -- or ran it
        or public.is_party_admin(p.id)
      )
  );
$$;

-- ---- RLS -------------------------------------------------------------------
alter table public.applause enable row level security;

-- Tallies are public knowledge, like the rest of the app.
drop policy if exists "applause: read" on public.applause;
create policy "applause: read" on public.applause
  for select to authenticated using (true);

-- The whole security boundary. UI hiding is not security: this is what stops a
-- crafted request clapping a song from another toque, someone who never played,
-- or a show the clapper had nothing to do with.
drop policy if exists "applause: clap once, in window, valid target" on public.applause;
create policy "applause: clap once, in window, valid target" on public.applause
  for insert to authenticated with check (
    from_user = (select auth.uid())
    and public.can_applaud(party_id)
    and (
      target_type = 'event'
      or (target_type = 'song' and exists (
            select 1 from public.performance perf
            where perf.id = performance_id
              and perf.party = party_id
              and perf.started_at is not null))
      or (target_type = 'performer' and exists (
            select 1 from public.performance perf
            join public.performance_user pu on pu.performance_id = perf.id
            where perf.party = party_id
              and pu.user_id = performer_id
              and pu.status = 'approved'))
      or (target_type = 'song_performer' and exists (
            select 1 from public.performance perf
            join public.performance_user pu on pu.performance_id = perf.id
            where perf.id = performance_id
              and perf.party = party_id
              and perf.started_at is not null
              and pu.user_id = performer_id
              and pu.status = 'approved'))
    )
  );

-- Un-clap: a mis-tap should be correctable. Can only ever reduce a tally.
drop policy if exists "applause: un-clap your own" on public.applause;
create policy "applause: un-clap your own" on public.applause
  for delete to authenticated using (from_user = (select auth.uid()));

-- No UPDATE policy on purpose: a clap is inserted or deleted, never edited.

commit;
