-- =============================================================================
-- Migration: placeholder (unregistered) band members (#78, phase 1)
-- Date: 2026-09-04
-- =============================================================================
-- A manager can list band members who don't have an app account yet, with the
-- instruments they play — so the band roster is complete before everyone joins.
-- Display-only: these don't reference a profile and can't be in a per-song
-- lineup until claimed (phase 2, #79 claim-link). Public read (roster display,
-- gated by can_see_band so a test band's placeholders stay hidden, #76);
-- managers write. instrument_ids is a plain array (no FK on array elements) —
-- fine for a display placeholder.
-- =============================================================================

begin;

create table if not exists public.band_pending_member (
  id             bigint generated by default as identity primary key,
  band_id        bigint not null references public.band (id) on delete cascade,
  display_name   text not null,
  instrument_ids bigint[] not null default '{}',
  created_at     timestamptz not null default now()
);
create index if not exists idx_band_pending_member_band on public.band_pending_member (band_id);

alter table public.band_pending_member enable row level security;

create policy "band_pending select visible" on public.band_pending_member
  for select to anon, authenticated using (public.can_see_band(band_id));
create policy "band_pending manager insert" on public.band_pending_member
  for insert to authenticated with check (public.is_band_manager(band_id));
create policy "band_pending manager update" on public.band_pending_member
  for update to authenticated using (public.is_band_manager(band_id));
create policy "band_pending manager delete" on public.band_pending_member
  for delete to authenticated using (public.is_band_manager(band_id));

commit;
